### ISSUE TITLE
Cannot find GTK+ library file "libgobject-2.0"

### ISSUE THREAD

**Issue by ghost** [egallesio/STklos#1]
I can't install some packages on Debian Linux using stklos-pkg. I did this:

sudo stklos-pkg --install stklos-gtklos
  
and i get this error:

(cd stklos-gtk-base; stklos-compile -c -L .. -o ../stklos-gtk-base.ostk stklos-gtk-base.spi)
**** Error while executing file "/usr/local/bin/stklos-compile"
	 Where: in error
	Reason: Cannot find GTK+ library file "libgobject-2.0"

  - error
  - find-gtk-library
  - #[closure 55f84fdf7600]
  - <<let/call>>
  - compile
  - #[closure 55f84fd4cac0]
  - <<let/call>>
  - include-file
  - cdr
  - compile-with-handler
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
Makefile:31: recipe for target 'stklos-gtk-base.ostk' failed
make: *** [stklos-gtk-base.ostk] Error 70

Also for installing some other packages like:
$ stklos-pkg --install stklos-posix-1.00.2
$ stklos-pkg --install soundex-0.2.0

i have these problem:

make: *** No rule to make target 'stklos-posix-1.00.2/stklos-posix-1.00.2.spi', needed by 'stklos-posix-1.00.2.ostk'.  Stop.

make: *** No rule to make target 'soundex-0.2.0/soundex-0.2.0.spi', needed by 'soundex-0.2.0.ostk'.  Stop.

**Comment by egallesio** [comment]
Hello teymurl,
The libgobject-2.0 is a library which should be available with Glib version  2. Perhaps, you only have Glib/Gtk version 3 installed on your machine. 
BTW, don't use sudo when installing STklos packages. They are searched in your own .stklos directory.

For stklos-pkg, don't specify the version when installing. You should have:
$ stklos-pkg --install stklos-posix
$ stklos-pkg --install soundex

Hope it helps.
