### ISSUE TITLE
duplicate parameter raises an uncatchable error?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#100]
Hi,

If I try to use the wrong number of parameters in a procedure call, STklos signals an error, which I can catch (this is useful in test procedures):

```
stklos> (with-handler (lambda (x) #f) (sqrt 1 2 3))
#f
```

But... Specifically for duplicate parameters, it won't be catchable:
```
stklos> (with-handler (lambda (x) #f) (lambda (x x) 1))
**** Error:
error: duplicate parameter x
	(type ",help" for more information)
```

Why? Is this intentional?

**Comment by egallesio** [comment]
Sort of: This is not an error which is cached at run time but at compilation time. Before the lambda is built, the compiler verifies that the parameter list is coherent. This permits to not test it at each call of the function, but only once. 
In your first example, the compiler doesn't now the arity of that `sqrt` will have at runtime
```scheme
(define (foo) list)
(let ((sqrt (foo)))
   (with-handler (lambda (x) #f) (sqrt 1 2 3)))
```

**Comment by jpellegrini** [comment]
Ok, I see -- it's  acompiler-error, not an error! Thanks!
