### ISSUE TITLE
examples of scripts (hello.stk and threads.stk) do not execute

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#123]
Hi,
The files
```
examples/hello.stk
examples/threads.stk
```
begin with a `#!`, so I suppose they are examples of files that can either be called  from the command line directly or compiled into `.ostk`.
However, it is not possible to execute  them because 

1. they do not have the executable bit set
2. even if the `x` bit is set, those won't work as scripts, because they use `#! /usr/bin/env stklos -f`, and `env` will not split the string following it. It actually tries to call a single binary named "`stklos -f`".

I can imagine two possible things to do:

1. remove the `#!` line from both. But then there would not be an example of STklos script runnable directly from command line anymore;
2. the `env` issue could perhaps be fixed in a maybe not very portable way with `env -S` (`-S` is "split arguments"), and the executable bit set. Then the examples would work from command line.

What do you think @egallesio ?

**Comment by jpellegrini** [comment]
I know this is not a big issue. I am only reporting it because Debian's lintian complains about these:

```
W: stklos: script-not-executable usr/share/stklos/1.50/Demos.d/hello.stk
W: stklos: script-not-executable usr/share/stklos/1.50/Demos.d/threads.stk
```

**Comment by egallesio** [comment]
Hi, 

Didn't know the `-S` option of `env`. That's interesting.
Anyway, I prefer to use  a starting line `#!/usr/bin/env stklos-script` since it gives lmore latitude for adaptation if needed. 

As you said, Making the script executable permits to show how to make a runnable script without compiling it. This could be interesting for the example directory. 

I modify the files.

**Comment by egallesio** [comment]
Yes we can  :smile:
I have change things a little bit: only `hello.stk` is executable now and the README explains the first line of a script and how to compile it. 

I close this issue.
