### ISSUE TITLE
Automake style warnings

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#126]
Automake 1.16 says:

```
doc/Makefile.am:42: warning: wildcard html/stklos-ref*.html: non-POSIX variable name
doc/Makefile.am:42: (probably a GNU make extension)
doc/Makefile.am:42: warning: wildcard html/*.css: non-POSIX variable name
doc/Makefile.am:42: (probably a GNU make extension)
doc/Makefile.am:45: warning: wildcard html/images/*: non-POSIX variable name
doc/Makefile.am:45: (probably a GNU make extension)
src/Makefile.am:33: warning: ':='-style assignments are not portable
src/Makefile.am:33: warning: or $(STRIP: non-POSIX variable name
src/Makefile.am:33: (probably a GNU make extension)
src/Makefile.am:111: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:25: warning: 'CFLAGS' is a user variable, you should not override it;
src/Makefile.am:25: use 'AM_CFLAGS' instead
```

Should we do something about these?

**Comment by egallesio** [comment]
I was just at the minute telling @jpellegrini that I have changed its correction in src/Makefile.am to delete  the warnings about line 33. 
Deleting the other warnings shoud be done too.

**Comment by jpellegrini** [comment]
One thing that lintian complains about is the version of libtool:

```
stklos source: ancient-libtool ltmain.sh 1.4.3
```

I'm not sure, however, wether upgrading it would fix warnings or get things even worse. I vaguely  remember that autotools used to break compatibility backards quite often.

**Comment by lassik** [comment]
Yes - autotools is a compatibility toolkit that isn't compatible with other versions of itself.

The latest stable version of libtool is 2.4.6. Maybe it's complaining that libtool 1 is too old since libtool 2 is the stable series.

**Comment by jpellegrini** [comment]
That said, it's just a warning. Debian packages don't need to have have that fixed in order to be in the archive...

**Comment by egallesio** [comment]
All the warnings are gone. and `lt-main.sh` is updated
This was a (really too) long fight with automake tools.

@jpellegrini: I had to change the strip stuff to remove the warning introduced by a previous PR. I'm not sure this is completely equivalent: The  value of the STRIP variable is  the one used at configuration time and not at install time. You can change it at install time with `make install STRIP="..."` (but not with `STRIP="..." make install` !). Is it a problem for you?

**Comment by jpellegrini** [comment]
> Is it a problem for you?

Not at all @egallesio ! It's great that you won the battle against autotools! :)

**Comment by egallesio** [comment]
Since, you both reacted favorably, I close this issue to clean the Issue list.
