### ISSUE TITLE
file-suffix when filename ends with a dot

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#127]
Currently `file-suffix` returns the same value for no extension, and a zero-length extension:

* `(file-suffix "foo") => ""`
* `(file-suffix "foo.") => ""`
* `(file-suffix "foo.ext") => "ext"`

Would it make sense to differentiate them:

* `(file-suffix "foo") => #f`
* `(file-suffix "foo.") => ""`
* `(file-suffix "foo.ext") => "ext"`

Or another way to do it (but this would change the return value for all calls of `file-suffix`, seriously breaking backward compatibility):

* `(file-suffix "foo") => `
* `(file-suffix "foo.") => "."`
* `(file-suffix "foo.ext") => ".ext"`

**Comment by lassik** [comment]
We're planning to write a pathname SRFI at some point, but work hasn't started yet. John Cowan has an early draft.

**Comment by egallesio** [comment]
You are right. Didn't notice the problem.
I think I prefer that `(file-suffix "foo")` returns `#f``. It is more coherent with functions such as `member` or `assoc`. You can test `(if (file-suffix path)  ... ... ))`.
I'll modify the implementation of STklos. It should not break existing code since having a  final dot should be rare. 

A problem still exists with dot files. What should be returned for paths such as ".." or ".profile"? 

Anyway, I can modify the current implementation of `file-suffix`.

**Comment by lassik** [comment]
Great! Sounds good.

> A problem still exists with dot files. What should be returned for paths such as ".." or ".profile"?

IMHO `.profile` should return `#f` and `.profile.sh` should return `".sh"` The algorithm would be:

* Find the last dot in the string; if none, return `#f`
* If the last dot was found at index 0, or right after a directory separator, also return `#f`.
* Otherwise return the substring after the dot.

**Comment by lassik** [comment]
Here is John's latest proposal, which is based on the Python standard library: https://github.com/johnwcowan/r7rs-work/blob/master/PathnamesPython.md

**Comment by egallesio** [comment]
In John proposal, the `path-suffix` is defined as 

> `(path-suffix path suffix)`
>
> Returns a the suffix of the filename (everything to the right of the final period) as a string. If there is no period, an empty string is returned. Note that this function does not discriminate between filenames without a period and filenames ending in a period; the latter should be avoided anyway, as they are not distinct on Windows.

As a result, the Windows remark makes me doubtful about the interest of changing things :confused:

**Comment by lassik** [comment]
Good point! I think the FAT file system stored filenames on disk as `NNNNNNNNEEE` (i.e. 8 bytes for name, 3 bytes for extension). So the dot is omitted to save space, which was important in DOS times. And when writing the directory entry, the dot is removed from the filename.

However, on Unix, `foo.` and `foo` are not considered the same filename. And there are also other pathnames translations that file systems do. E.g. NTFS (Windows NT) and HFS (MacOS) are case sensitive, so "AAaa" and "aaaa" are the same file internally. Some file systems do Unicode normalization.

Since there are so many different translations, and they are context-dependent and difficult to understand, I would recommend having APIs that treat pathname strings exactly as given and don't try to guess what the file system will do. Hence, treating `foo` and `foo.` differently would be reasonable.

The simplest API is something like `(path-without-suffix "foo.bar") => "foo"` and `(path-suffix "foo.bar") => ".bar"` and an empty suffix returns `""` or `"."` depending on whether or not there is a dot at the end. This has the advantage that `(string-append (path-without-suffix p) (path-suffix p))` always returns `p`.

**Comment by lassik** [comment]
@johnwcowan: This thread may interest you since you're preparing the pathname SRFI.

**Comment by egallesio** [comment]
What John says is that on Windows (even Win10).  "foo" and "foo." denote the same file. 
So,on this OS,  `(path-suffix "foo.")` and `(path-suffix "foo")` will return a different value whereas they refer the same file.

**Comment by lassik** [comment]
Yes, but `(path-suffix "foo.bar")` and `(path-suffix "foo.BAR")` will also return a different value even though they refer to the same file. There's no way we can cover all of the pathname normalization rules used by the dozens of different file systems out there.

**Comment by egallesio** [comment]
So you think that John will change the specification of `path-suffix` to add the dot in the suffix if present?

**Comment by johnwcowan** [comment]
I have changed `path-suffix` and its relatives so that ".foobar" and "foobar" do not have a suffix and so `#f` is returned.   Consequently, the remark about Windows is gone.

**Comment by egallesio** [comment]
Hi @lassik,
Finally pushed a commit for this issue.

**Comment by lassik** [comment]
Great! Thanks for attending to this!

**Comment by lassik** [comment]
Looks good to me, so closing the issue.
