### ISSUE TITLE
"every" from bonus.stk is not fully compatible with SRFI-1

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#137]
Hello @egallesio !

`every` from `bonus.stk` does not return the last PRED value, as the SRFI requires:

> The iteration stops when a false value is produced or one of the lists runs out of values. In the latter case, every returns the true value produced by its final application of `pred`.

This makes the reference tests for SRFI-134 fail.

Since this is not in `srfi-1.stk`, but in `bonus.stk`, I am not sure which you'd prefer:

* keep the version of `every` in `bonus.stk` as is, and makea new one in `srfi-1.stk` (then requiring srfi-1 would override the embedded version of `every`)
* replace the `every` code in `bonus.stk`

If you tell me which one you'd like to have, I can make a PR.

**Comment by egallesio** [comment]
Hi @jpellegrini,

This is a bug in fact. The implementation should be compatible in `bonus.stk` with SRFI-1 (I suppose that `any` implementation  is incorrect too). If you have a PR ready, I'll be happy to apply it. Otherwise, I can do it too.
Thanks for signaling it (and preparing SRFI-134, visibly :wink: )

**Comment by jpellegrini** [comment]
Hi @egallesio !
Yes, I'll send a PR if you can wait a little (maybe tomorrow morning)

**Comment by jpellegrini** [comment]
I managed to do it. Submitted!

**Comment by egallesio** [comment]
Hello @jpellegrini , can we close the Issue now?

**Comment by jpellegrini** [comment]
Hi @egallesio !
Yes, all tests pass and everything seems to be fixed. :)
