### ISSUE TITLE
SRFI 180 (JSON)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#16]
Hi,
JSON is quite important these days, and SRF 180 has an example implementation. It would be nice to have it in STklos!
J.

**Comment by egallesio** [comment]
I agree that having JSON is important and in fact, you already have access to
a JSON reader/writer through a SmPkg package. This was a port of the Dominique
Boucher's parse he wrote in 2007.

You can install it with `$ stklos-pkg -i json`

Hereafter, is a simple example:

```scheme
stklos> (require "json")
stklos> (import json)
stklos> (with-input-from-string "[1, 2.4, \"a\", true, false, null]" json-read)
(1 2.4 "a" #t #f #(json-null))
stklos> (define h (make-hash-table))
;; h
> (hash-table-put! h "a" 2.5)
> (hash-table-put! h "b" #f)
> (json-write h)
{"b": false, "a": 2.5}
```
Of course, this is less complete than the draft SRFI, but it's already here.

Porting SRFI-180  when it will be finalized is on my todo list.

**Comment by jpellegrini** [comment]
SRFI-180 is now final!

I am working on getting the reference implementation to work on STklos, but there are some issues (some tests do not pass), so it may take a while.

Specifically, the test `i_number_huge_exp.json` raises an "`Unexpected object`" condition; and several string tests fail because the parsed string has trailing zero characters.

**Comment by jpellegrini** [comment]
@lassik  have you ran the tests from the reference implementation?

This:

```
(define-test i_number_huge_exp.json
  (check #(0.4) (parse "./files/i_number_huge_exp.json")))
```

seems wrong. The file contains

```
[0.4e00669999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999969999999006]
```

which should be parsed as a husrfi-180@srfi.schemers.orgge number, or as infinity.

@lassik  have you ran the tests from the reference implementation?

This:

```
(define-test i_number_huge_exp.json
  (check #(0.4) (parse "./files/i_number_huge_exp.json")))
```

seems wrong. That file contains

```
[0.4e00669999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999969999999006]
```

which should be parsed as a huge number, or as infinity.

The github repository for SRFI-180 does not accept issue reports, I'll try a PR...

**Comment by jpellegrini** [comment]
Also, as far as I could check, although infinities are not allowed in the JSON spec, it is usual to, when reading a huge number, parse it as infinity. Python3, Emacs Lisp, Javascript and Ruby do that, but the reference implementation doesn't seem to allow infinities (they're explicitly ruled out in `raise-unless-valid?`.

**Comment by jpellegrini** [comment]
So, I can skip that test - it is the only one that fails outside the Unicode area.

Now, the implementation seems to get confused with Unicode:

In one of the tests, it is supposed to read and reproduce the string  "Полтора Землекопа".
It parses and returns a string which has length 33, although the string has 17 UTF8 characters.

It is actually doing UTF-8 encoding in UTF-8! (The UTF8 encoding of the string has 33 characters)...

I'm not sure where the problem is, but it'll take some time to debug this.

**Comment by egallesio** [comment]
I have started too the port of SRFI-180. I have not concentrated too much  on the code itself but on the tests. Anyway, if you want, you can continue since I will not have a lot of time to complete it soon. 

I have seen the bug with `i_number_huge_exp.json`. I think that the result should be `#(+inf.0)` in this particular case. 

However, I'm not very found of the tests of this SRFI, they are probably useful for the SRFI developer, less for a simple port and to verify non regression of the integration. The `files` directory occupies 1.7Mb! and I don't want to add so much data for only one SRFI. Furthermore, even the "big" tests are not very convoluted.  So, IMHO STklos should be able to run all the SRFI tests, but probably not integrate all of them in the distribution. This is mostly due to the usage of very small files. 

BTW, I have made I have a bunch of other tests which have spotted some bugs in the symbols management (it is pushed on github). These tests could be added to the ones kept from  the ones of SRFI-180. To reduce, the usage of small files, I used here strings (the idea come from an egg implementation of JSON for Chicken, an I think it's cool) :

```scheme
(test-json "complex.1" ; example 1 from RFC 4627
           '((Image
              (Width . 800)
              (Height . 600)
              (Title . "View from 15th Floor")
              (Thumbnail
               (Url . "http://www.example.com/image/481989943")
               (Height . 125)
               (Width . "100"))
              (IDs . #(116 943 234 38793))))
#<<JSON
{
    "Image": {
        "Width":  800,
        "Height": 600,
        "Title":  "View from 15th Floor",
        "Thumbnail": {
            "Url":    "http://www.example.com/image/481989943",
            "Height": 125,
            "Width":  "100"
        },
        "IDs": [116, 943, 234, 38793]
    }
}
JSON
)
```
I prefer this solution to the usage of files, which make tests hard to debug.
  
BTW, I think that here strings could  a good idea for a SRFI. What do you think @lassik?

**Comment by egallesio** [comment]
> In one of the tests, it is supposed to read and reproduce the string "Полтора Землекопа".
> It parses and returns a string which has length 33, although the string has 17 UTF8 characters.

Can you tell me please, what is the test with this string? I'll try to have a look at it. 
Thanks.

**Comment by jpellegrini** [comment]
Hi,
>  Can you tell me please, what is the test with this string? I'll try to have a look at it.
> Thanks.

It is this one:

```
(define y_object_string_unicode.json
      (check '((title . "Полтора Землекопа")) (parse "./files/y_object_string_unicode.json")))
```

**Comment by jpellegrini** [comment]
> Anyway, if you want, you can continue since I will not have a lot of time to complete it soon.

I will try again later -- I got into something else now...

>  So, IMHO STklos should be able to run all the SRFI tests, but probably not integrate all of them in the distribution

Sure!

**Comment by egallesio** [comment]
Hi @jpellegrini , 

The test about "Полтора Землекопа" is OK for me (at least if inlined in the test file).  ;-)

**Comment by jpellegrini** [comment]
Hi @egallesio !
With the reference implementation?

I have the reference implementation added in the `srfi-180` branch in my Github copy of STklos... That test, and a couple of others, do not pass.

I'll try using your tests

**Comment by jpellegrini** [comment]
The tests you included didn't all pass for me:

```
stklos> (load "do-test.stk")
stklos> (main #t)
==== Testing Numbers  ...                                        passed
==== Testing Keywords  ...                                       passed
==== Testing call/cc & dynamic-wind  ...                         passed
==== Testing String Ports (SRFI 6)  ...                          passed
==== Testing File Ports  ...                                     passed
==== Testing Threads  ...                                        passed
==== Testing SRFIs  ...                                          passed
==== Testing JSON  ...                                           **** Error:
try-load: bad textual port `#[input-port '/home/jeronimo/pkg/scheme/STklos-jpellegrini/tests/test-json.stk' (4)]'
	(type ",help" for more information)
stklos>
```

If I comment out the "complex.3" test, it works.

I am using the reference implementation, which is in that branch I told you. I'll look into this a bit more later.

**Comment by jpellegrini** [comment]
All tests that are included in STklos now pass here.
Maybe this issue could be closed?

* STklos has a small and efficient VM (suitable for embedded devices). With the SRFIs that are being added, it is becoming a really fantastic choice for Scheme programming!

**Comment by egallesio** [comment]
>     * STklos has a small and efficient VM (suitable for embedded devices). With the SRFIs that are being added, it is becoming a really fantastic choice for Scheme programming!

Thank  you!
Concerning the many supported SRFIs, most of them are present thanks to **your** hard work.

**Comment by lassik** [comment]
It's wonderful to see so much good work go into Scheme at such a fast pace lately!
