### ISSUE TITLE
make clean does not delete srfis-data.scm

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#162]
I ran the tests for SRFI-207 and they kept failing because feature "srfi-207" was missing... Took me a while to actually understand what was going on: since `srfis-data.scm` wasn't deleted, it was not being generated when I ran make.
Since it's an auto-generated file, shouldn't it be removed by `make clean`?

**Comment by egallesio** [comment]
You are correct. I thought it was not possible to delete it since it is includes in the boot image. However, if the list changes, the file is rebuilt before the image reconstruction. It was necessary for the first bootstrap, but no more now. 

Thanks for signaling this issue.
