### ISSUE TITLE
The `gc` and `address-of` procedures are listed in the manual as R5RS procedures, but they're not...

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#166]
Hello!
https://stklos.net/Doc/html/stklos-ref-4.html#Standard-Procedures
I'd make a PR if I knew where to change that information.

**Comment by egallesio** [comment]
Hi @jpellegrini 
Thanks for signaling it. 
The correction is simple: In the comment containing the documentation you can put a tag which indicates the category of the thing described (if no tag is present, it is assumed to be a R5RS procedure).
So the correction for `gc` consists only to replace
```
/*
<doc  gc
```
by
```
/*
<doc  EXT gc
```
(`EXT `stands for extended STklos procedure)

**Comment by jpellegrini** [comment]
Hi @egallesio !
I see those are fixed in git, but the documentation on the website still has the previous version...

**Comment by egallesio** [comment]
You are right. But the site documentation correspond to the one of the release. 
BTW, it is probably time to have a new version.

**Comment by jpellegrini** [comment]
>  BTW, it is probably time to have a new version.

That's great! :)   I know it's a small thing, but don't forget to take a look into #165 (documentation of (gc) for the new version (that is, if the PR is OK for you)

**Comment by egallesio** [comment]
Done! 
Thanks for the documentation fix.
