### ISSUE TITLE
log does not accept a second argument

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#170]
According to R7RS, it should accept an optional base as 2nd argument (the "z2" argument, on page 38).

**Comment by jpellegrini** [comment]
By the way, the C "`log`" function that is passed to `DEFINE_PRIMITIVE` is the native `log` from the C math library? I couldn't find it in the STklos sources.

**Comment by egallesio** [comment]
Oops didn't see this addition to R5RS (I think). 
Yes i use the Clib log functionn, but I use the C preprocessor transcendental to build the primitive (not really useful her since, the macro is nearly the DEFINE_PRIMITIVE itself.
