### ISSUE TITLE
Intention: SRFI-170

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#172]
Hello @egallesio !
Just wanted to let you know I'm slowly working on SRFI-170 (Posix API). It'll take a while because it's large and must be written in C, but doable. :)

I have already implemented sections 3.5, "Process state" and 3.11, "Environment variables".

**Comment by jpellegrini** [comment]
> I have already implemented sections 3.5, "Process state" and 3.11, "Environment variables".

And part of 3.6, "User and group database access"!
Learning a bit more about STklos...

**Comment by jpellegrini** [comment]
I just realized that SRFI 170 requires SRFI 19. Actually, SRFI-120 also requires 19, so it makes more sense to do 19 first.
But I remember I've tried that one first and had problems. I'll check again.

Meanwhile, I'll try to keep 170 mostly ready (will represent "time objects" in an ad-hoc way, and get everything together when SRFI-19 is ready.

@egallesio -- you wouldn't be working on SRFI-19, by any chance, would you?

**Comment by egallesio** [comment]
> Just wanted to let you know I'm slowly working on SRFI-170 (Posix API). It'll take a while because it's large and must be written in C, but doable. :)

You have a lot of courage! It is a long SRFI to implement. Thanks a lot for volunteering to do it.

Perhaps you can find some useful code in https://github.com/egallesio/stklos-posix
(not sure).

> you wouldn't be working on SRFI-19, by any chance, would you?

In fact, I have a long-standing version of SRFI-19 under the hood!

However, the SRFI sample implementation have been modified several times since its first publication and some fixes have even been published since my last modification (15 years ago!!). It would be probably useful to look at the discussion archive and report new fixes in it. 

I join the version I have in this message

[srfi-19.zip](https://github.com/egallesio/STklos/files/6129639/srfi-19.zip)

**Comment by jpellegrini** [comment]
> You have a lot of courage! It is a long SRFI to implement. Thanks a lot for volunteering to do it.

No problem!
In fact, I think I have not more than 2/3 of it ready.
 
> Perhaps you can find some useful code in https://github.com/egallesio/stklos-posix
> (not sure).

It does help!
But SRFI-170 requires us to raise some specific new condition containing errno. I've been doing that in my implementation.

> In fact, I have a long-standing version of SRFI-19 under the hood!
> 
> However, the SRFI sample implementation have been modified several times since its first publication and some fixes have even been published since my last modification (15 years ago!!). It would be probably useful to look at the discussion archive and report new fixes in it.
> 
> I join the version I have in this message

Thank you!
I'll take a look later.
Meanwhile, I'll test SRFI-170 with an ad-hoc time struct.

**Comment by egallesio** [comment]
> Meanwhile, I'll test SRFI-170 with an ad-hoc time struct.

Perhaps it is a good idea to keep  temporary struct because SRFI-19 is quite large and using it for POSIX is perhaps a  bit overkill. No?

**Comment by jpellegrini** [comment]
> > Meanwhile, I'll test SRFI-170 with an ad-hoc time struct.
> 
> Perhaps it is a good idea to keep temporary struct because SRFI-19 is quite large and using it for POSIX is perhaps a bit overkill. No?

Yes -- thank you for suggesting that!

Prehaps keep it the time structure in STklos core, since it may also be used by other SRFIs that do not depend on each other (19, 120)?

**Comment by jpellegrini** [comment]
It's already there!   Structure `%time`.

I've finished most of this one, but there are some hard parts yet to go.
But I believe STklos 1.70 will have SRFI-170.  :)

**Comment by egallesio** [comment]
> But I believe STklos 1.70 will have SRFI-170. :)

:smiley:

**Comment by jpellegrini** [comment]
So... It's there already! :)
