### ISSUE TITLE
Should arrays be a native type or should they be a struct? (SRFI-25)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#177]
@egallesio --

I am working on SRFI-25. It seems that SRFI-164 adds to SRFI-25 (and does not supersede it); and the newer array/interval SRFIs (122, 179) are very different (and large), so it seems  to be worth working on 25 (please correct me if I'm wrong).

I wonder if arrays should be a `struct` or a new boxed type defined in `stklos.h`.

This is how I thought they could be implemented:

A SRFI-25 array has a `shape`, which is a list of begin and end indices, so the index for a particular dimension may not start at zero. In order to have fast access to array elements, I thought I'd add a `tc_array`  as this:

```
struct array_obj {
  stk_header header;
  unsigned int rank;
  int *shape;
  unsigned int *offsets;
  unsigned int *multipliers;
  int size;
  SCM data[1];
};
```

* the array is stored in row-major mode, so it has a data vector, `SCM data[1]`
* `shape` is a list of `int`s containing beginning and end of each dimension. So a 2x3 matrix with indices starting at `1` would have shape `1 3 1 3`.
* `offset` (size is half the size of `shape`) -- a list of `unsigned`s that have the amount to be added to each index when accessing it (so we don't need to use `shape` and do a subtraction for each dimension)
* `multipliers` is the list of `unsigned`  numbers that would be used in each dimension as multipliers, to access the element.

So, since the array would be stored in row-major mode, access to element in position `i j k l m` would be

```
data[ multiplier[0]*i +
      multiplier[1]*j +
      multiplier[2]*k +
      multiplier[3]*l +         
      multiplier[4]*m ]
```

So `array-ref` would use the following code:

```
// ref[] is a vector with the indices requested
unsigned final_pos = 0;
for (idx=0; idx < ARRAY_RANK(a);  idx++) {

  // check bounds
  if ( (ref[idx] < ARRAY_SHAPE(a)[idx*2]) || (ref[idx] >= ARRAY_SHAPE(a)[idx*2-1]) ) STk_error("out of bounds");

  final_pos += ARRAY_MULTIPLIER(a)[idx] * (ref[idx] + ARRAY_OFFSET(a)[idx]);
}
return ARRAY_DATA(a)[final_pos];
```

So I could think of 3 options:

1. implement in STklos core. The advantages are:

* It hides the implementation details (offset, multipliers...). With a structure, the user would be able to `(describe my-array)` and see its internals.
* It seems faster than using `struct-ref` for each array access.

However, it would not be possible to leave arrays as  a loadable library, since the `tc_array` type would have to be included in `stklos.h` anyway.

2. implement as structure

* does not make the core larger

But may be slower and leak implementation details

3. include `tc_array` and macros `ARRAY_...` in `stklos.h` but the rest of the implementation in `srfi-25-impl.c` which would have the best of both approaches, however it would be ugly.

What do you think?

**Comment by jpellegrini** [comment]
I forgot to ask: were you already working on SRFI-25? If not, I think I can get it ready quickly -- in either of the three ways proposed in my previous message.

**Comment by egallesio** [comment]
Hi @jpellegrini, 

I didn't found time to look in detail at your questions. I will have a look asap. 

However, we **already** have a SRFI-25 implementation for STklos. The implementation was done by Heinrich Wolf. It is available by as a ScmPkg. It would be cool to have it native (rather than as a ScmPkg, since it is more or less  the last interesting package available from `scmpkg`) . The architecture of Heinrich's code is not simple (and I'm not sure that it is easy to adapt a ScmPkg in a SRFI available in the distribution). However, there is a really nice documentation in Heinrich's package.  

There are 2 tar.gz (a generic one and a customization). If you have enough courage to look at this code... 

The files are joined: 

[srfi25_stklos-0.1.0.tar.gz](https://github.com/egallesio/STklos/files/6165749/srfi25_stklos-0.1.0.tar.gz)
[srfi25-0.1.0.tar.gz](https://github.com/egallesio/STklos/files/6165750/srfi25-0.1.0.tar.gz)

**Comment by jpellegrini** [comment]
OK - I have seen the implementation by Heinrich. I think it is worth having arrays as a loadable SRFI, or maybe into the core, though.

Both approaches are simple, but

1. If we have it as a structure (hence loadable as `.ostk` + `.so`, then all array data must be encoded as Scheme objects inside a struct. Then, the data used to calculate indices would need to be restored from Scheme vectors each time a reference is made
2. If we create a `tc_array` in the core, we can use plain C, so references will be faster. But the array type will be hardcoded there, and maybe we can then only have the functions loaded from `srfi-25.{ostk,so}`.

I'm beginning to think approach 2 is better... What do you think?

**Comment by egallesio** [comment]
I think that the second approach is better. We can just have the minimal support in the base, and everything else in the SRFI implementation.  This will not overload too much the base, and will permit a better/faster implementation of arrays. 
If you have enough courage to implement this, it would be really really great.

**Comment by jpellegrini** [comment]
Ok... I have most of it done. Will probably finish by the end of the week. :)

**Comment by jpellegrini** [comment]
> Ok... I have most of it done. Will probably finish by the end of the week. :)

Hm, maybe a bit longer than that. 
I have written it in C, and it mostly works, but there are a few bugs I need to fix.

**Comment by jpellegrini** [comment]
@egallesio  we could keep discussing in the PR thread, and close this. Do you agree?

**Comment by egallesio** [comment]
You are right. I close this issue.
