### ISSUE TITLE
SUPPORTED-SRFIS

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#19]
The file SUPPORTED-SRFIS seems to not have been modified in a long time.

Perhaps it would be nice to have a single source for the list of supported SRFIs? The webpage could perhaps point to an updated version of that file?

**Comment by egallesio** [comment]
You are right, I have missed the update of this file. 

However, maintaining the list of SRFIS is a real mess. In fact we need two lists:
1. one list for the current version which contains the SRFIs of that given version
2. one list (on the site) for the last stable release (to not advertise for things which are in the git tree and not in the stable version). 

In fact, the source list for the SRFIs is the one in the `doc/skb` directory, which is the list of documented SRFIs. I have made a script to update the file SUPPORTED-SRFIS when a new SRFI is documented. The script in charge of the web site will now take a snapshot a this list when building the site. 

I hope that these mods will permit to have something more close from reality. 

Thanks to have spotted this issue.
