### ISSUE TITLE
SRFI 25 failing tests: equality predicates

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#197]
Hi @egallesio !

Some SRFI-25 tests are failing because of this:

```
stklos> (define a (array (shape 0 2 0 2 0 2) -1 -2 -3 -4 -5 -6 -7 -8))
stklos> (define d (share-row a 0))

stklos> d
#,(<array> (0 2 0 2) -1 -2 -3 -4)
stklos> (equal? d #,(<array> (0 2 0 2) -1 -2 -3 -4))
#f       ;; oooh, it's because d is a shared array, and the literal array given for comparison is not!

stklos> (define e (array-copy d))   ;; aha, e makes a non-shared copy of d.
#,(<array> (0 2 0 2) -1 -2 -3 -4)
stklos> (equal? e  #,(<array> (0 2 0 2) -1 -2 -3 -4))
#t
```

So, right now `a` and `b` are `equal?` if the are reeeealy equal: if one is shared and the other isn't, then `equal?` will return `#f`.

Is this the behavior we want?  (The SRFI text is not clear about that)

**Comment by egallesio** [comment]
Hi @jpellegrini, 

I don't know, if shared array should be equal? to arrays. But the current behavior seems correct for me. Perhaps, we could have a `array-equal?` (not found of this name)  predicate  which doesn't make the difference (as `string-ci=?` which doesn't care of the case used). What do you think.

In the meantime, I have pushed new tests where we compare a copy of the tested shared array to its external representation.

**Comment by jpellegrini** [comment]
> Perhaps, we could have a `array-equal?` (

`array=?` maybe?

**Comment by jpellegrini** [comment]
> In the meantime, I have pushed new tests where we compare a copy of the tested shared array to its external representation.

Did you push to master?  I saw no new commits...

**Comment by jpellegrini** [comment]
It looks like implementations differ a lot on this:

* Racket's `equal?` will return `#f`, even for arrays that are identical (not sharing elements).
But Racket has a `array-equal?` procedure that returns `#t`.
* Gauche's `equal?` returns `#t`, as well as `array-equal?`.
* Larceny's `equal?` returns `#f`, even for arrays that are identical (not sharing elements). There is no `array-equal?`
* Kawa's `equal?` returns `#t`, even for shared arrays!
* Chicken's `equal?` returns `#t`, even for shared arrays!

**Comment by jpellegrini** [comment]
> Did you push to master? I saw no new commits...

Sorry, I see you pushed it now!

**Comment by egallesio** [comment]
> Did you push to master? I saw no new commits...
My bad. It should be OK now.

**Comment by egallesio** [comment]
> Sorry, I see you pushed it now!

No it's me :confused:

**Comment by egallesio** [comment]
> It looks like implementations differ a lot on this:
> 
>     * Racket's `equal?` will return `#f`, even for arrays that are identical (not sharing elements).
>       But Racket has a `array-equal?` procedure that returns `#t`.
> 
>     * Gauche's `equal?` returns `#t`, as well as `array-equal?`.
> 
>     * Larceny's `equal?` returns `#f`, even for arrays that are identical (not sharing elements). There is no `array-equal?`
> 
>     * Kawa's `equal?` returns `#t`, even for shared arrays!
> 
>     * Chicken's `equal?` returns `#t`, even for shared arrays!

And the solution I propose is not compatible with the existing ones!!  Reminds https://xkcd.com/927/

**Comment by jpellegrini** [comment]
I see there is already a C function `test_equal_array` that you included in `srfi-25-impl.c`.
It could be used to make another primitive `array-equal?`, OR, we could implement something in scheme, like

```
(define (array-equal? a b)
  (and (equal? (array->list (array-shape a))
               (array->list (array-shape b)))
       (equal? (array->list a)
               (array->list b))))
```
or a variant of this accepting multiple arguments.
What do you think?

**Comment by jpellegrini** [comment]
> ```
> (define (array-equal? a b)
>   (and (equal? (array->list (array-shape a))
>                (array->list (array-shape b)))
>        (equal? (array->list a)
>                (array->list b))))
> ```
Although that would not be memory efficient (allocates new lists). It could be done is scheme with `shape-for-each`, maybe. But perhaps it would be better in C?

**Comment by egallesio** [comment]
The function `test_equal_array` is the function that is used by `equal?`. In fact, with the last modification I make to the base, you can define the C function which will be called by `equal?` when you define a new type. 
For the function `array-equal?` a Scheme version should be OK I think .

**Comment by jpellegrini** [comment]
> For the function `array-equal?` a Scheme version should be OK I think .

I'll get that done later. Without copying the array.

**Comment by jpellegrini** [comment]
This is done, right?
