### ISSUE TITLE
PORTING-NOTES

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#21]
It seems that PORTING-NOTES is also outdated...
Maybe it would be nice to re-check it?

I have two suggestions:
1. it runs on Banana Pi, and quite probably on the Raspberry Pi, running armbian.
2. it runs on OpenWRT (ARM and MIPS), and I have tested this on a few platforms.

I can open a pull request with that information, but if you are willing to revamp the file, maybe adding or removing fields in the entries, I can wait and make the pull request after that.

**Comment by egallesio** [comment]
Hi, 

Yes, the information in this file was really old. I have updated it (but I'm not too found of the result). You can modify as you like  to insert  the platforms you tested.

Thanks again for your work.

**Comment by jpellegrini** [comment]
Ok, I'll do that later.

**Comment by egallesio** [comment]
In any case, to be bullet-proof , my push script to github recreates automatically this  file from the content of the `srfi.stk` file in the documentation. 

May I close this issue?

**Comment by jpellegrini** [comment]
> In any case, to be bullet-proof , my push script to github recreates automatically this file from the content of the `srfi.stk` file in the documentation.

Are you sure this is the right issue? This one is about PORTING-NOTES (which I guess can be closed)... You're talking about the other, SUPPORTED-SRFIS?

**Comment by egallesio** [comment]
Oops, you are correct. I was thinking of SUPPORTED-SRFIS. Please, forget my previous message.
Anyway, in your last message you said that you want to do something later, but the ports you've done on Arms and Mips architectures are already described. Do you think to something else?

**Comment by jpellegrini** [comment]
> Anyway, in your last message you said that you want to do something later, but the ports you've done on Arms and Mips architectures are already described. Do you think to something else?

I think it's all there already!

**Comment by egallesio** [comment]
OK! 
So i close this issue.
