### ISSUE TITLE
Tests hang sometimes

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#215]
A build without threads always finishes running the tests, it seems (I've run the tests more than 50 times).

But the threaded build sometimes gets locked for some reason. Usually while testing SRFI 41 (or the one after it, maybe), but not always there. This happens on both Android and Linux/amd64.

Could this be related to the GC issue?

(I'm sorry - I've been reporting lots of problems lately...)

**Comment by jpellegrini** [comment]
I'll try using different versions of  libgc later.

**Comment by jpellegrini** [comment]
I tried the development version of libgc and tests also hang sometimes with it.

Now, I tried passing `_REENTRANT` and `GC_LINUX_THEADS` in `CFLAGS` and tests ran 100 times without hanging, but it crashes as reported in issue #208.. So, it seems like the solution to that issue had problems.
I'll take another look into the libgc documentation.

**Comment by jpellegrini** [comment]
Compiled without any of those flags, and included `#define GC_THREADS` in `stklos.h`.
It did show the same memory related problems as before.

So, `_REENTRANT` is not related to it; in fact, it seems from the documentation that `_REENTRANT` shoudl only be used when compiling the collector itself, not the application. Our problem is with `GC_THREADS`...

**Comment by jpellegrini** [comment]
I also tried using gcc 8 and gcc 10, both lead the those same problems.

**Comment by jpellegrini** [comment]
STklos 1.60 behaves the same way as git head... 
Still checking.

**Comment by jpellegrini** [comment]
Aha!
I tried STklos 1.00 and the code that triggers the memory problem,
```
(let ((v #f))
  (dotimes (i 1000000)
    (set! v (make-vector 100000))
    (display "."))
  (newline))
```
does **_NOT_** cause any problems when included in the tests!

So something between STklos 1.00 and STklos 1.60 triggered the problem.

**Comment by jpellegrini** [comment]
I found the commit that causes the memory problems!

`0be2e08b208bcc913a112a4c36f3ad0d8fce2611` (2020-06-29 11:21:15)
"Adaptation of the threads for Android"

It's related to threads, and there were changes to `pthreads.c`, `misc.c`, autoconf scripts...

**Comment by jpellegrini** [comment]
> `0be2e08b208bcc913a112a4c36f3ad0d8fce2611` (2020-06-29 11:21:15)
> "Adaptation of the threads for Android"

It really is this commit, since the previous snapshot works OK, and this one doesn't. But I have  read everything that was commited, and I can't see what could be causing the problem!

**Comment by jpellegrini** [comment]
Oh, found something else!

If I comment out the threads test from `do-test.stk`:
  (load "test-fport.stk")
;;  (load "test-threads.stk")  ;; <== removed
  (load "test-srfi.stk")           ;; <== this is where thebug was triggered
  (load "mem.stk")
  (load "test-md5.stk")
```

then it all works fine!

So the problem is actually triggered in the threads tests, which were indeed changed in that commit!

**Comment by jpellegrini** [comment]
And here is the culprit:

```
(test "Terminate the current thread (suicide)"
      45
      (letrec* ((val 42)
                (t   (make-thread (lambda ()
                                    (set! val (+ val 3))
                                    (thread-terminate! t)))))
        (thread-start! t)
        (let Loop ()
          (when (= val 42)
            ;; we need to wait
            (sleep 10)
            (Loop)))
        val))
```

If I comment out this test, there is no high memory consumption.
If I put it back in, then STklos starts eating lots of memory!

So it's related to `thread-terminate!`, which is what this commit was about after all...

**Comment by jpellegrini** [comment]
By the way...  I don't think it would fix this problem, but what about not letting it enter an infinite loop there?  The test could try 10 times and fail if the result is still 42.

**Comment by jpellegrini** [comment]
But if I just put these on the REPL:

```
(letrec* ((val 42)
                (t   (make-thread (lambda ()
                                    (set! val (+ val 3))
                                    (thread-terminate! t)))))
        (thread-start! t)
        (let Loop ()
          (when (= val 42)
            ;; we need to wait
            (thread-sleep! 10)
            (Loop))

(let ((v #f))
  (dotimes (i 1000000)
    (set! v (make-vector 100000))
    (display "."))
  (newline))
```

the problem does *not* happen, as I would expect...

**Comment by jpellegrini** [comment]
It seems that the problem is present in previous versions of STklos; it's just that this particular commit to the tests triggers it. I just tried the code  on 1.40 and the problem is there too.

**Comment by jpellegrini** [comment]
@egallesio sorry for the number of messages!

See, it seems that even 1.00 had the problem:

```
(define t   (make-thread (lambda () (thread-terminate! t))))

(thread-start! t)

(let ((v #f))
  (dotimes (i 1000000)
    (set! v (make-vector 100000))
    (display "."))
  (newline))
```

That code makes STklos (1.00) eat up all available memory!

**Comment by jpellegrini** [comment]
@egallesio --
I was working on SRFI-194, and noticed that sometimes, some of its tests give wrong results, and sometimes not.
Now -- both SRFI-194 and its tests are *deterministic*. The random numbers generated should be all determined by the seeds, which are set to the same values always.
And each time it fails, it seems to be in a different location of the tests
So, maybe that is related to this issue?
I can push my srfi-194 branch to github if that helps.

And later I'll run a memory check on this computer (although I doubt this is the issue)

**Comment by jpellegrini** [comment]
Hmm, one of the SRFIs where tests hang _**on my amd64 PC**_ is 64.  When I runit on a MIPS router, I get this:

```
==== Testing Threads  ...                                        passed
==== Testing SRFIs  ...                                          
      1    2    4    5   13   25   27   37   41   48   51   54
     60   62   64Killed
```

In a second run, all SRFI tests passed.

So, the same problem that made it hang on an intel architecture with `libc` killed it on MIPS with `musl`. I'm not sure if this information is useful, but well, maybe this helps.

**Comment by egallesio** [comment]
I think that this corrected now. I have also tested it multiple times 

> "make test" was run withu hanging
>   - on Linux 300 times
>   - Macos Mojave 100 times
>   - Android 100 times

**Comment by jpellegrini** [comment]
Yes, checking right now!

**Comment by egallesio** [comment]
Thanks for you help @jpellegrini

**Comment by jpellegrini** [comment]
Hi @egallesio !
Tests seem to pass on OpenWRT/MIPS, but on Android there is a problem with SRFI-144 (probably some easy-to-fix glitch). I've opened a separate issue for that.

**Comment by jpellegrini** [comment]
@egallesio -- the problem with SRFI-144 is not related to this issue. It's just that some dynamic library isn't being opened. The hanging tests problem seems to be fixed, definitely!

**Comment by egallesio** [comment]
Great! I close this one.
