### ISSUE TITLE
Installing packages fails

### ISSUE THREAD

**Issue by xgqt** [egallesio/STklos#219]
It seems that the required directories in /tmp are not getting created

![image](https://user-images.githubusercontent.com/47485207/118385358-a389c300-b5fd-11eb-87b0-854114c4681d.png)

**Comment by xgqt** [comment]
![image](https://user-images.githubusercontent.com/47485207/118385376-d5028e80-b5fd-11eb-9141-f8e260f9967c.png)

**Comment by jpellegrini** [comment]
@egallesio -- I have just tried it here and got the same error on a Debian system.

**Comment by egallesio** [comment]
Thanks @xgqt for signaling the problem. 
I have seen this a couple of days ago on my machine too. I think that I have broken it when  I have used the new SRFI-170 primitives in the package manager itself. 
 I'll try to fix it quickly.

**Comment by jpellegrini** [comment]
Hello,
It looks like that problem is solved, although copiling the smtp package seems to not work:

```
make[2]: Entering directory '/tmp/user/1000/36810044Nb60s/ssl/stklos/src'
stklos-compile -C -o ssl-inc.c ssl.stk
Compilation time 0 ms
gcc-10 -fpic -nostdlib -I/usr/local/include/stklos -I/usr/local/include/stklos/gc -g -O2 -DSSL_VERSION=\"1.0.0\" -c ssl.c
ssl.c: In function ‘STk_module_info’:
ssl.c:126:34: error: ‘__module_infos’ undeclared (first use in this function); did you mean ‘STk_module_info’?
  126 |    return STk_read_from_C_string(__module_infos);
      |                                  ^~~~~~~~~~~~~~
      |                                  STk_module_info
ssl.c:126:34: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:42: ssl.o] Error 1
```

**Comment by jpellegrini** [comment]
> is solved

I mean, in git HEAD

**Comment by xgqt** [comment]
> Hello,
> It looks like that problem is solved, although copiling the smtp package seems to not work:
> 
> ```
> make[2]: Entering directory '/tmp/user/1000/36810044Nb60s/ssl/stklos/src'
> stklos-compile -C -o ssl-inc.c ssl.stk
> Compilation time 0 ms
> gcc-10 -fpic -nostdlib -I/usr/local/include/stklos -I/usr/local/include/stklos/gc -g -O2 -DSSL_VERSION=\"1.0.0\" -c ssl.c
> ssl.c: In function ‘STk_module_info’:
> ssl.c:126:34: error: ‘__module_infos’ undeclared (first use in this function); did you mean ‘STk_module_info’?
>   126 |    return STk_read_from_C_string(__module_infos);
>       |                                  ^~~~~~~~~~~~~~
>       |                                  STk_module_info
> ssl.c:126:34: note: each undeclared identifier is reported only once for each function it appears in
> make[2]: *** [Makefile:42: ssl.o] Error 1
> ```

same for me

**Comment by egallesio** [comment]
This shoul be OK now. 
I have tested all the ScmPkgs. Almost all are running with the current version of STklos

If I'm correct, here is the current state: 
- [x] awk-0.0.3 (tuning)
- [x] ccnum-0.2.0
- [x] csv-0.5.0 (tuning)
- [x] edefine-0.0.1 (tuning)
- [x] egg-crc-0.0.2 (tuning)
- [x] egg-xosd-0.0.5 (tuning)
- [x] error-0.0.4 (tuning)
- [x] fixnum-0.0.1 (tuning)
- [ ] htmlprag-0.16.2 (tuning)
- [x] http-utils-0.0.2 (tuning)
- [x] json-1.0.0
- [ ] mail-compose-1.0.0
- [x] match-0.0.1 (tuning)
- [x] modeline-0.0.9
- [x] numspell-0.1.0
- [x] parameter-1.0.0
- [x] pregexp-1.0.1
- [ ] pstk-1.0.0 (tuning)
- [ ] quoted-printable-1.0.0
- [x] recette-1.0.2 (tuning)
- [x] record-0.0.3 (tuning)
- [x] rfc3339-0.2.0
- [x] rfc822-1.0.0
- [x] smtp-1.0.1
- [x] soundex-0.2.0
- [x] srfi1-0.0.1 (tuning)
- [x] srfi11-0.0.1 (tuning)
- [x] srfi13-1.0.1 (tuning)
- [x] srfi14-1.0.1 (tuning)
- [x] srfi16-0.0.1 (tuning)
- [x] srfi2-1.0.0 (tuning)
- [x] srfi23-0.0.1 (tuning)
- [x] srfi25-0.1.0 (tuning)
- [x] srfi26-1.0.0 (tuning)
- [x] srfi28-1.0.0 (tuning)
- [x] srfi4-1.0.0 (tuning)
- [x] srfi6-1.0.1 (tuning)
- [x] srfi66-1.0.0 (tuning)
- [x] srfi69-1.0.0 (tuning)
- [x] srfi8-0.0.1 (tuning)
- [x] srfi9-1.0.0 (tuning)
- [x] ssl-1.0.1 (tuning)
- [x] stklos-fuse-0.90.6
- [x] stklos-gtk-base-1.0.0
- [x] stklos-gtk-canvas-1.0.0
- [x] stklos-gtk-glade-1.0.0
- [x] stklos-gtklos-1.0.0
- [x] stklos-posix-1.00.2
- [x] stklos-ssax-5.1.2
- [x] strnatcmp-0.0.1
- [x] tabexpand-0.1.0
- [x] url-utils-0.0.1 (tuning)

**Comment by egallesio** [comment]
Note that this list must be heavily cleaned, since most of these codes are more than 15 years old and are not really useful. For instance, all the SRFIs listed above are now in the standard distribution. And I'm not sure that porting `pstk` to the current STklos has a real interest today.

**Comment by xgqt** [comment]
Works for me now after most recent update.
Thank you.
Closing.
