### ISSUE TITLE
Cannot install stklos-gtk-base

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#22]
Hello,
I am running a Debian system, and  tried to run the GTK example on the website.

```
$ stklos-pkg -s
Synchronizing server "main"
   "http://www.stklos.net/ScmPkg/main" ... done
Synchronizing server "stklos"
   "http://www.stklos.net/ScmPkg/stklos" ... done
```
Ok, so the repository is up to date. Now,
```
$ stklos-pkg --install stklos-gtk-base
(cd stklos-gtk-base; stklos-compile -c -L .. -o ../stklos-gtk-base.ostk stklos-gtk-base.spi)
**** Error while executing file "/usr/local/bin/stklos-compile"
	 Where: in error
	Reason: Cannot find GTK+ library file "libgobject-2.0"

  - error
  - find-gtk-library
  - #[closure 7fb90abb9380]
  - <<let/call>>
  - compile
  - #[closure 7fb90acc4880]
  - <<let/call>>
  - include-file
  - cdr
  - compile-with-handler
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
make: *** [Makefile:29: stklos-gtk-base.ostk] Error 70
```

That library is provided by Debian package `libglib2.0-dev`, which is installed, and the files are in place:
```
$ ll /usr/lib/x86_64-linux-gnu/|grep libgobject
-rw-r--r-- 1 root root    728178 May 29 16:24 libgobject-2.0.a
lrwxrwxrwx 1 root root        19 May 29 16:24 libgobject-2.0.so -> libgobject-2.0.so.0
lrwxrwxrwx 1 root root        26 May 29 16:24 libgobject-2.0.so.0 -> libgobject-2.0.so.0.6400.3
-rw-r--r-- 1 root root    383192 May 29 16:24 libgobject-2.0.so.0.6400.3
```

Is it a path issue? Do I need to tell stklos-pkg where to find the libraries?

**Comment by egallesio** [comment]
Libraries are searched in `/usr/lib` and `/usr/local/lib` only. 
Try to set the shell variable `STKLOS_GTK_DIR` to `/usr/lib/x86_64-linux-gnu/` before running stklos-pkg and it should be OK. 
Tell me if it works for you.

**Comment by jpellegrini** [comment]
Thank you @egallesio it works!

It would be nice to add this to the tutorial on the webpage -- setting `STKLOS_GTK_DIR` may be needed -- and if it's needed, it will be both during installation with `stklos-pkg` and during program execution.

Anyway, the example worked perfectly.

**Comment by egallesio** [comment]
You are correct and I have added a little note about this variable on the web site.

**Comment by jpellegrini** [comment]
Thanks @egallesio -- but I can't see thenote you added. Is it on the GTK programming tutorial page, https://stklos.net/stklos-gtk-base.html ?

**Comment by egallesio** [comment]
It is on the front page https://stklos.net/screenshots.html which gives access to this page. But if you didn't see, it is probably because it is not so well placed. So, I have added this  note again on the 3 explanations pages.

**Comment by jpellegrini** [comment]
Yes, I see now!

For me this issue is resolved. Can I close?
