### ISSUE TITLE
Should numerator always be non-negative?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#220]
R7RS says that `denominator` should always return a non-negative number. _It says nothing about `numerator`._

For `(numerator -2/3)`: Chez, Chibi, Chicken, Gambit, Gauche, Guile, Kawa, Loko, MIT Scheme and Racket  all return -2.

Should STklos perhaps also return -2? (Currently it returns 2).

**Comment by lassik** [comment]
If all other major Scheme implementations return a negative number, that's a pretty strong precedent that STklos should as well.

**Comment by egallesio** [comment]
> If all other major Scheme implementations return a negative number, that's a pretty strong precedent that STklos should as well.

and one can expect that dividing one by the other produces a result with a  good sign!

I pushed a commit that correct this. Thanks @jpellegrini for signaling it.
