### ISSUE TITLE
Generated srfi-25-incl.c is not a C program

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#227]
While cross-compiling, the generated `srfi-25-incl.c` is not a C program. It looks like `stklos-compile` generates the usual  bytecode file.

```
lib/srfi-25/srfi-25-incl.c 
#!/usr/bin/env stklos-script
; A -*- Scheme -*- generated file *DO NOT EDIT**
STklos (#:version "1.60" #:globals (array-for-each-index array->vector array->list
```

I'll check what could be causing this.

The relevant compilation output is this:
```
make[5]: Entering directory '/home/jeronimo/pkg/openwrt-21.02/build_dir/target-mips_24kc_musl/STklos-a0c9b2c5ff3c4b2c10cab8522fd11d0ed7ac53aa/lib/srfi-25'
/home/jeronimo/pkg/openwrt-21.02/build_dir/target-mips_24kc_musl/STklos-a0c9b2c5ff3c4b2c10cab8522fd11d0ed7ac53aa/build_install/usr/local/bin/stklos-compile -o srfi-25-incl.c srfi-25.stk
Compilation time 28 ms
mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/home/jeronimo/pkg/openwrt-21.02/build_dir/target-mips_24kc_musl/STklos-a0c9b2c5ff3c4b2c10cab8522fd11d0ed7ac53aa=STklos-a0c9b2c5ff3c4b2c10cab8522fd11d0ed7ac53aa -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro   -fpic -nostdlib -I../../src -I/home/jeronimo/pkg/openwrt-21.02/staging_dir/target-mips_24kc_musl/usr/include   \
-c -o srfi-25.o srfi-25.c
In file included from srfi-25.c:29:
srfi-25-incl.c:1:2: error: invalid preprocessing directive #!
 #!/usr/bin/env stklos-script
```

**Comment by jpellegrini** [comment]
Hm, the compiler is being called without the `-C` option. More later.

**Comment by egallesio** [comment]
> Hm, the compiler is being called without the `-C` option. More later.

Yep. The new `utils/tmpcomp` command adds it when the output file is suffixed by a '.c'. 
You have probably using an old script in your chain.

**Comment by jpellegrini** [comment]
> You have probably using an old script in your chain.

But it is downloaded and unpacked every time I compile. I think some env variable is not being expanded or used properly. I'll check.

**Comment by jpellegrini** [comment]
Hm, it's using `stklos-compile` directly instead of calling `../utils/tmpcomp`.
Still checking

**Comment by egallesio** [comment]
Hi @jpellegrini ,

The new version of `tmpcomp` is now more "compatible" with `stklos-compile`. This should fix this issue (I hope so).

**Comment by jpellegrini** [comment]
Hm, does `stklos-copile` need `bigloo-support`?

```
/home/jeronimo/pkg/openwrt-21.02/build_dir/target-mips_24kc_musl/STklos-1f25e39dcf362fa18c5da991a14856992ab9b7e7/build_install/usr/local/bin/stklos-compile -o stklos-pkg main.stk
**** Error while executing file "/home/jeronimo/pkg/openwrt-21.02/build_dir/target-mips_24kc_musl/STklos-1f25e39dcf362fa18c5da991a14856992ab9b7e7/build_install/usr/local/bin/stklos-compile"
	 Where: in open-input-file
	Reason: could not open file `"bigloo-support.stk"'

  - open-input-file
  - <<let/call>>
  - include-file
  - #[closure 7f52f1260780]
  - <<let/call>>
  - #[closure 7f52f12606e0]
  - call-with-values
  - dynamic-wind
  - try-load
  - %try-load
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
```

**Comment by jpellegrini** [comment]
> Hm, does `stklos-copile` need `bigloo-support`?

Or actaully, does `stklos-pkg` need `bigloo-support`?

**Comment by jpellegrini** [comment]
> Or actaully, does `stklos-pkg` need `bigloo-support`?

Got that fixed; I can pass `-L ../lib/` to `stklos-compile.
There are still things not working with cross-compilation, but those are related to the cross-compiling script, not STklos itself (I think).

**Comment by egallesio** [comment]
> Or actaully, does stklos-pkg need bigloo-support?

Yes, to permit adding code written in Bigloo (without modification). I'm not sure that this is the sort of thing that is still useful, since ScmPkg is not really used. ScmPkg was an attempt that the author of Bigloo and I tried to develop at the same time that Marc Feeley created Snow (in fact, ScmPkg was snow at the beginning, but we divert from the Marc version rapidly).
 
Given that ScmPkg failed, the support for other Scheme dialect should be deleted.  Another thing on my TOD list :tired_face:

**Comment by jpellegrini** [comment]
@egallesio  no problem here -- I can work around that temporarilly, with the `-L` option.
This issue is actually not the real problem. I think #228 is a problem -- it seems that only `.stk` files from `lib/` are being installed. I can't see why...

I have manually removed my local STklos installation from `/usr/local/`, then  ran distclean, then autoreconf, configure and make and make install (from your `master` branch), and... There are no `.ostk` files in `/usr/local/share/stklos/1.60`! See that issue (#228)

**Comment by jpellegrini** [comment]
> Given that ScmPkg failed, the support for other Scheme dialect should be deleted. Another thing on my TOD list tired_face

Let me know how I can help! I know it's a lot of work...  Anyway, 1.70 will be a huge enhancement over 1.60!

**Comment by jpellegrini** [comment]
I think this issue is not valid anymore...

**Comment by egallesio** [comment]
> Let me know how I can help! I know it's a lot of work... Anyway, 1.70 will be a huge enhancement over 1.60!
Thanks for helping. 
I think that pkgman should disappear as soon as we can use another package manager (Akku, Snow, ...). But for doing that, it is necessary to support `define-library`. I have some stuff in the works that I need to finish on this point

**Comment by egallesio** [comment]
> I think this issue is not valid anymore...

OK I close this issue.
