### ISSUE TITLE
Untracked pkgman files

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#232]
`git status` shows the following untracked files after a build:

```
pkgman/lang-bigloo.inc
pkgman/lang-chicken.inc
pkgman/lang-mzscheme.inc
```

Should these be added to `.gitignore`?

**Comment by egallesio** [comment]
Weird. Normally they are now deleted when the `stklos-pkg`  has been successfully built.

**Comment by egallesio** [comment]
Hi @lassik,
I have verified on a Mac Mojave version and these files are not present after a build. Weird

**Comment by lassik** [comment]
OK, finally found what causes it! `./configure --prefix=$HOME/.local`. If I leave out the `--prefix` I don't get the leftover files either.

**Comment by egallesio** [comment]
I'll have a look at that. Thanks for the issue analysis.
