### ISSUE TITLE
SRFI-144: gcc complains about `round (log2 DBL_MAX)` 

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#234]
Hi @egallesio !
In SRFI-144, it seems that `round (log2 DBL_MAX)` isn't being accepted by some versions of gcc:

```
srfi-144.c: In function 'STk_srfi_144_flnormalized_fraction_exponent':
srfi-144.c:207:27: error: expected ')' before numeric constant
         e = 3 + round(log2 DBL_MAX);
                           ^
                           )
srfi-144.c:207:23: error: incompatible type for argument 1 of 'round'
         e = 3 + round(log2 DBL_MAX);
                       ^~~~
In file included from srfi-144.c:3:
/home/jeronimo/pkg/openwrt-21.02/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/include/math.h:323:19: note: expected 'double' but argument is of type 'double (*)(double)'
 double      round(double);
                   ^~~~~~
```

But not on all machines I tried, so it seems that it depends on gcc version (not portable, then?)

**Comment by jpellegrini** [comment]
This happens on my Android device, and also on the OpenWRT build environment.

**Comment by jpellegrini** [comment]
gcc-10.2.0_musl also fails on OpenWRT.
I think it's something else.

**Comment by egallesio** [comment]
This problem prevents to rebuild the Docker image on Docker hub. :disappointed:

**Comment by egallesio** [comment]
gcc works for me but not clang
Replacing `double e = round(log2 DBL_MAX);` by `double e = round(log2(DBL_MAX));` works

**Comment by jpellegrini** [comment]
Then the fix is simple! :)

**Comment by egallesio** [comment]
I have pushed a commit, and we'll see if docker hub rebuild it :crossed_fingers:

**Comment by jpellegrini** [comment]
> `round(log2 DBL_MAX);`

Anyway... I'm not sure I remember this being legal C. Is it something new? `(log2 DPL_MAX)` looks a lot like Lisp :smile:

**Comment by egallesio** [comment]
Is it Ok for you? because the image was not build by DockerHub for a mysterious reason (but it  compile srfi-144).

**Comment by jpellegrini** [comment]
> Is it Ok for you?

Yes, it compiles on all platforms now!

**Comment by jpellegrini** [comment]
> the image was not build by DockerHub for a mysterious reason

See PR #235 -- would that be the cause?

**Comment by egallesio** [comment]
It seems to have to do with the integration of the Localization SRFI (I suppose that the LANG variable is not defined or something like that).
 I will look at it tomorrow.

**Comment by jpellegrini** [comment]
> It seems to have to do with the integration of the Localization SRFI (I suppose that the LANG variable is not defined or something like that).
> I will look at it tomorrow.

Also, `srfi-29.ostk` was not being installed because of the conflict I mentioned in PR #235 ...

**Comment by jpellegrini** [comment]
But even fixing the Makefile, something goes wrong during tests in Android and OpenWRT. Not on my PC.

**Comment by egallesio** [comment]
The problems came from SRF-29. It should be corrected now.

**Comment by egallesio** [comment]
Closing this issue.
