### ISSUE TITLE
Cannot load SRFI-144 on Android

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#236]
Hi @egallesio !
This only happens with SRFI-144 (other hybrid SRFIs like 25 and 170 load fine).

```
stklos> (require "srfi-144")
**** Error:
%file-informations: cannot open object file /data/data/com.termux/files/usr/lib/stklos/1.60/srfi-144.so (dlopen failed: cannot locate symbol "__eqtf2" referenced by "/data/data/com.termux/files/usr/lib/stklos/1.60/srfi-144.so"...)
```

**Comment by jpellegrini** [comment]
Just confirmed: SRFI-144 is the only one that fails.

This:

```
rm tests/srfis/144.stk
make test
```

works perfectly on Android with zero errors.

**Comment by egallesio** [comment]
Hi @jpellegrini ,

This is corrected. In fact , LLVM support for `math.h` is buggy: the implementation of `fmodl` produces  code which uses the undefined function _eqtf2,

However, when correcting this problem, tests didn't pass. A problem come from the function `lgamma_r` which was not declared (but present in the runtime). The other problem came from a test which produce `e`. I have replaced this test by `test-approx` (see the test file). I hope my fix is correct.

**Comment by egallesio** [comment]
Can you close, if it is OK for you?

**Comment by jpellegrini** [comment]
It works now! :)
Thanks @egallesio
