### ISSUE TITLE
Termux compiled STklos successfully!

### ISSUE THREAD

**Issue by sts-q** [egallesio/STklos#247]
; Termux compiled STklos successfully!
     ;
     ; pkg install libpcreposix
     ; pkg install automake
     ; pkg install libgc
     ; ./configure
     ; make
     ; make test
     ; src/stklos
     ;
     ;   \
     ;    \
     ;   / \
     ;  /   \
     ;
     ;  :-)

**Comment by egallesio** [comment]
Really happy to see that you were able @sts-q to compile it on Android.

**Comment by egallesio** [comment]
Closing this "issue" to keep the list short. Thanks for pointing out the successful build.
