### ISSUE TITLE
Avoid unsafe C string functions

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#252]
Replace `sprintf()` with `snprintf()`?

**Comment by egallesio** [comment]
Yep, you are right.
BTW, It is on my TODO list since a long time, but an open issue will make it probably happen before :wink:

**Comment by egallesio** [comment]
All the `strcpy` and `sprintf` are now rewritten in `snprintf`
There are no more `strcat` in the C sources. 
@lassik, may I close this issue?

**Comment by lassik** [comment]
Great! Sure.
