### ISSUE TITLE
|2| is not supposed to be a number

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#266]
Hi @egallesio !

Looks like vertical-bar-delimited identifiers may be misread as numbers:
```
stklos> (+ |2| 3)
5
```

**Comment by lassik** [comment]
```Scheme
stklos> (number? |2|)
#t
stklos> (symbol? |2|)
#f
```

**Comment by egallesio** [comment]
> ```scheme
> stklos> (number? |2|)
> #t
> stklos> (symbol? |2|)
> #f
> ```

It is false but, at least, it is  coherent  :wink:

It is fixed. I'll commit soon.

**Comment by jpellegrini** [comment]
It works now! :)

```
stklos> |-2|
**** Error:
%execute: variable `-2' unbound
```
