### ISSUE TITLE
STklos says complex numbers are not numbers

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#270]
Not really a big deal, and not strictly an error, but I'd expect to be told that "complex numbers cannot be compared", not that "0+1i is  a bad number"...
The error message is the same given when I try to compare a number to a string.

Now, it is true that `0+1i` is a "bad" number in that context, because it can't be used, but in STklos, "`bad number`", or "`bad <type>`" usually means the object is not of that type (and in this case, it seems to be telling me that `0+1i` is not a number!)

```
stklos> (< -1 (sqrt -2))
**** Error:
<: `0+1.4142135623731i' is a bad number
	(type ",help" for more information)

stklos> (< (sqrt -1) (sqrt -2))
**** Error:
<: `0+1i' is a bad number
	(type ",help" for more information)
```

**Comment by egallesio** [comment]
Hi @jpellegrini ,
You are right. I'll correct this message.

**Comment by lassik** [comment]
R7RS says that `<` is defined only on real numbers, so a logical error message would be `0+1i is not a real number`.

**Comment by egallesio** [comment]
Hi @jpellegrini and @lassik,

This is fixed in last bunch of commits

I think I can close this one.
