### ISSUE TITLE
Shouldn't completely embedded SRFIs be provided by default?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#277]
For example,
```
stklos> (require "srfi-169")
**** Error:
load: cannot load file "srfi-169"
```
Hmm, but we *do* have SRFI-169 available! It's just not necessary to load it.

So far I see that 18, 23, 30, 34, 38, 39, 55, 62, 87, 88 145, 169, 176, 193, 219 are not automatically provided.

But 0, 5, 35, 36, 61 are.

SRFI 89 loads a file, but does not provide "srfi-89" (and STklos issues a warning)

**Comment by egallesio** [comment]
> For example,
>
> ```
> stklos> (require "srfi-169")
> **** Error:
> load: cannot load file "srfi-169"
> ```
>
> Hmm, but we _do_ have SRFI-169 available! It's just not necessary to load it.

 That's "normal": `require` permits to load a file if it has not yet be loaded before. The mechanism is independent of SRFIs, and requiring a file that does not exist is an error.

On the counterpart, the `require-feature` is one construct that you can use that will load the file if it is necessary and which serves only for SRFIs. It uses the data in `srfis-data.scm` to see if a file must be loaded to use a given SRFI. 
 

>
> So far I see that 18, 23, 30, 34, 38, 39, 55, 62, 87, 88 145, 169, 176, 193, 219 are not automatically provided.
>
> But 0, 5, 35, 36, 61 are.
>
For 0, it is necessary to access the other SRFIs.  However, I don't understand what you mean for the others.

```scheme
stklos> (provided? "srfi-5")
#f
stklos> (provided? "srfi-36")
```

> SRFI 89 loads a file, but does not provide "srfi-89" (and STklos issues a warning)

Oops, I'll correct that. Thanks.


BTW, I say that require is not related to SRFI, but the code I have added this week (and that I'll commit soon), transforms `(require "srfi-N")` in a `(require "srfi/n")` (plus an implicit import in STklos module). Probably it should be changed later, when all the srfis will be rewritten as libraries.

**Comment by jpellegrini** [comment]
Ok, thanks @egallesio for the explanation and sorry for the noise!
I suppose we can close this then?

**Comment by egallesio** [comment]
No problem @jpellegrini . That's true that the documentation is not clear on this point.

**Comment by egallesio** [comment]
Closing this issue
