### ISSUE TITLE
Hash tables with equality predicate string-ci=? give wrong result

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#29]
Something strange is happening with hash tables with equality predicates:

```
stklos> (define h (make-hash-table string-ci=?))
;; h
stklos> (hash-table-set! h "Aa" 10)
stklos> (hash-table-ref h "Aa")
10
stklos> (hash-table-ref h "aa")
10
stklos> (hash-table-ref h "AA")
**** Error:
hash-table-ref: entry not defined for key `"AA"' in table `#[hash-table 7faa9be531e0]'
	(type ",help" for more information)
```

Requiring SRFI-69 and repeating the above gives the same result.

Anyway, `string-ci=?` seems to be fine:

```
stklos> (string-ci=? "Aa" "AA")
#t
```

The problem would be in `hash.c`, I suppose?

**Comment by egallesio** [comment]
In fact this behavior is "normal". The comparison function is used for the items which are in the very same bucket. Here the standard  hash function returns (by luck) the same bucket for "Aa" and "aa", but a different one for "AA". So, when you search "aa" or "Aa", you'll find the value stored in the list associated to the bucket. Conversely , the "AA" hash value returns a different bucket (an empty one), and the value is not found

Consequently, you need to give also a hash function as 3rd parameter. This is described in the [maks-hash-table documentation](https://www.stklos.net/Doc/html/stklos-ref-4.html#--index-entry-33519).

In fact, this is probably not a so good idea to let the user give a comparison function without giving  hash function, as it is error prone.

**Comment by jpellegrini** [comment]
Hmm, the Guile tests for SRFI-171 (transducers) fail on STklos because of this. I'll check if it's just the tests or the implementation itself.

**Comment by jpellegrini** [comment]
The documentation says alist->hashtable accepts a hash function, such as hash-table-hash, but something doesn't seem to be working:

```
stklos> (define replace-alist '((1 . s) (2 . c) (3 . h) (4 . e) (5 . m)))

stklos> (alist->hash-table replace-alist string-length)
**** Error:
string-length: incorrect number of parameters (2) in call to `#[primitive string-length]'
	(type ",help" for more information)
stklos> (alist->hash-table replace-alist hash-table-hash)
**** Error:
hash-table-hash: incorrect number of parameters (2) in call to `#[primitive hash-table-hash]'
	(type ",help" for more information)
```

**Comment by jpellegrini** [comment]
Ok then! I've adapted SRFI-171.
