### ISSUE TITLE
Prepend expression when compiling a file? (Needed for SRFI 138)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#293]
SRFI-138 requires only one thing: an executable that compiles a file with specific command-line arguments.
These are:

```
-D name
    Add name to the list of feature identifiers maintained by the Scheme implementation for the purpose of executing the program in the text file pathname. 
-A directory
    Append directory to the list of directories that are searched in order to locate imported libraries. 
-I directory
    Prepend directory to the list of directories that are searched in order to locate imported libraries. 
-o outfile
    Use the pathname outfile, instead of the default a.out, for the executable file produced. 
```

I have an implementation ready, except for the `-D` option, which would define, from the command line, a feature to be regognized when the compiled program is executed.

As far as I can see, this would require changes to compfile. Maybe an option in `compile-file` to accept also an expression to be compiled in the beginning of the file?

```scheme
(compile-file input output :prepend expr)
```

Then I'd be able to do

```scheme
(compile-file input output :prepend '(begin (select-module SRFI-0) (set! *all-features* (cons 'whatever *all-features*) (select-module stklos) )
```

The program that the SRFI wants would be this:

```scheme
(define-macro (string-push-back! x s)
  `(set! ,s (string-append ,s ,x)))

(define (go args)
  (format #t "CMD: ~s" (format "stklos-compile ~a" args)) ; for debugging, will be removed later
  (system (format "stklos-compile ~a" args)))

(define (main cmd-line-args)
  (let ((args ""))
    (parse-arguments cmd-line-args
                     "Usage: compile-stklos [ OPTION ... ] [ FILE ]"
                     "Options:"
                     (("output" :alternate "o" :help "output file" :arg outfile)
                      (string-push-back! (format " -o ~a " outfile) args))
                     (("append" :alternate "A" :help "append directory to path" :arg dir)
                      (string-push-back! (format " --append-load-path=~a " dir) args))
                     (("include" :alternate "I" :help "prepend directory to path" :arg dir)
                      (string-push-back! (format " --prepend-load-path=~a " dir) args))
                     (("define" :alternate "D" :help "define feature" :arg feature)
                      (format #t "Don't know how to define a feature for the program being compiled!~%"))
                     (("help" :alternate "h" :help "show help")
                      (arg-usage (current-error-port))
                      (exit 0))
                     (else
                      (if (= 1 (length other-arguments))
                          (go (string-append args (car other-arguments)))
                          (format #t "Unrecognized options: ~S~%" other-arguments))))))
```

**Comment by jpellegrini** [comment]
Or maybe also add some primitive to add a feature, so I could do

```scheme
(add-feature 'whatever)
```
instead of
```scheme
(compile-file input output :prepend '(begin (select-module SRFI-0) (set! *all-features* (cons 'whatever *all-features*) (select-module stklos) )
```

@egallesio are these ideas OK? If so, I can implement them.

**Comment by jpellegrini** [comment]
See PR #295

**Comment by egallesio** [comment]
Hi @jpellegrini,

I don't really understand why we'll need a relay file such as this one, if we except the -D option (more on that later). I have the feeling that the actual `stklos-compile` should be OK for a `compile-r7rs` (or to be placed in the `COMPILE_R7RS` environment variable). The only points we have to resolve:
 * there is no '-A' option, but this can be added 
 * the prepend option use `-L` instead of `-I`. However, this is incoherent with `stklos` command, which already uses `-I` for prepending a path. I think that we should change the `-L` shortcut for `stklos-compile` to `-I` and we're done.
 
 
 About the `-D` option, you are right, we'll probably have to add to modify the compile-file to prepend some code to the file. BTW, note that we already have `srfi0-register-feature!` which permit to add a feature to STklos. Of course, we can add this option to the actual `stklos-compile`. If we have it for compiled code, it should be also proposed when we run the interpreter (but we already have a `-D` option). 
 However, I must admit that I don't really see the interest or any usage of this option.
 
 In the meantime, I add the `-A` option and modify the `-L`  to `-I` in `stklos-compile`

**Comment by jpellegrini** [comment]
Ok @egallesio !
Later this week I'll try to implement the `-D` flag.

What is preferable?
1. Some way to pass s-expressions to the compiler so it injects before the code, or
2. (less general but simpler) some way to pass features (symbols) to the compiler so it defines them in the program being compiled

**Comment by egallesio** [comment]
I don't know what is simpler.  In fact. 2 is simpler, but I'm not sure that the compiled code should not have the defined features when it will be run later. So we probably need that the feature be defined at compile time and at run time (or only at run time?). 

For me, all this stuff is not clear: suppose that we have a feature called `debug`, used to show some traces. Do we want to have
1. traces when compiling
2. traces generated in the compiled code
3. both? 

We can also have a -D option which just says that is is not supported yet :wink:

**Comment by jpellegrini** [comment]
Hm, I think both would be interesting.
From what I understand from the SRFI, the `-D` flag is for compile time. But we can ask in the SRFI list.
(STklos will be the first to implement it!)

**Comment by jpellegrini** [comment]
> (STklos will be the first to implement it!)

Sorry - second. I see that Larceny has it. I'll see how Larceny implements it.

**Comment by jpellegrini** [comment]
What about this?

* `-k` will compile expressions into the program (at the beginning; run-time)
* `-e` already does the other thing: evaluates the expression before compiling (compile-time)
* `-D` is only for compatibility with the SRFI, and will use `-k` to include `srfi0-register-feature!` in the compiled program

I already have a patched version of `(compile-file ...)` that accepts a list of expressions to compile. I'm working on the rest.

**Comment by jpellegrini** [comment]
Updated the PR. I *_think_* it works

**Comment by jpellegrini** [comment]
Actually, use `-e` to include the feature. The compiler does the explansion of the `cond-expand`, so the feature should be available at compile time.

**Comment by jpellegrini** [comment]
And the PR was merged, so I think we can close this! :)
