### ISSUE TITLE
How to migrate SRFI-70?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#297]
SRFI 70 requires changes to several standard procedures. STklos already has them implemented in the way SRFI-70 wants, so there was no need, for example, to redefine `exact->inexact` and some others.
And SRFI-70 was never a module: it is a file that redefines some procedures and defeins some new ones.

Now, if we're going to define it as an R7RS library, do we need to export all symbols in the SRFI? Because most of them would be bound to STklos primitives.

**Comment by egallesio** [comment]
Hi @jpellegrini, 

Functions from the SRFI should be in a module.

> Now, if we're going to define it as an R7RS library, do we need to export all symbols in the SRFI? Because most of them would be bound to STklos primitives.

Yes we need to export them, because you cannot assume that you have all STklos functions available. You can use a smaller subset than STklos, when using this SRFI . For instance,

```scheme
(define-library (test)
  (import (scheme r5rs)
          (srfi 70))
  (begin
    (display (finite? 10))))
```
