### ISSUE TITLE
Where does the STklos name come from?

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#3]
STklos is a continuation (no pun intended) of STk, and the STk name comes from Scheme and the Tk GUI toolkit. The STKlos name obviously derives from STk, but where does the `los` suffix come from?

**Comment by lassik** [comment]
Aha :) Quoting from http://kaolin.unice.fr/STk/:

> STk embeds also an efficient CLOS like object oriented system, called STklos, which provides: multiple inheritance, generic functions, multi-methods, a MOP (Meta Object Protocol)

**Comment by egallesio** [comment]
Yes  indeed this is the composition of STk (which was the composition of Scheme and Tk) and CLOS. 
I'm not very imaginative for naming things :-)

**Comment by lassik** [comment]
I think it's a nice name :) At first I thouht the ST comes from Smalltalk, though the Smalltalk object system is somewhat different.
