### ISSUE TITLE
STklos tries to load the same module twice, in tests

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#321]
With PR #320, this happens:

```
==== Testing SRFIs  ...                                          
      1    2    4    5   13   15   17   25   26   27   28   29
     37   41   48   51   54   60   62   64   70   74   87   94
     95  113  117  118  127  128  129  130  132**** Error while executing file "do-test.stk"
	 Where: in try-load
	Reason: module `srfi/132' already loaded
```

STklos tests SRFI 95 fine, but 95 imports 132, so when it gets to 132... It tried to re-load the module and crashes.

**Comment by egallesio** [comment]
I think that I have corrected the problem. However, I was not able to merge your PR about SRFI-95 since if we load the tests for 95, we have 260 fail tests in SRFI 132.  Not found why.

**Comment by jpellegrini** [comment]
THanks @egallesio ! This is not an issue anymore... SRFI-95 works (but it seems to bread 132 for some reason -- I've desribed it in the PR)
