### ISSUE TITLE
Shouldn't the SCHEME module be immutable?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#335]
Hi @egallesio !
As per the issue title... Since, as in `boot.stk`, 
```scheme
;;; The SCHEME module is a copy of the STklos module before the user
;;; may have the possibility to modify standard bindings.
;;; If a module needs to be sure to have the original bindings, it
;;; can import this module which will be visible before the STklos
;;; module. Note that this is only partially true since bindings
;;; in SCHEME module are mutable
```
then shouldn't the `SCHEME` module be immutable? (<s>I actually didn't find the definition of modules in the code...</s> Ok, I found - it's in `env.c`)

I'm asking because I would like to (in the future) count on being able to get the original bindings of the standard Scheme symbols.

**Comment by egallesio** [comment]
It is on my TODO list....

**Comment by jpellegrini** [comment]
Can I help?
Is if the only module that should be immutable, or should it be a property of modules? The second sounds better.
What about this?

* Include a mutable flag in all modules
* When a module is created, it is mutable by default, except for the `SCHEME` module
* Add a `module-mutable?` predicate
* Later we may decide if other modules should be mutable, or if it should be possible to lock or unlock a module.

This sounds easy, I could make a PR in the next days. Is that OK?

**Comment by jpellegrini** [comment]
Hi.
I think I got it working... :)
See PR #340 .

**Comment by jpellegrini** [comment]
Hi @egallesio !
I think this one is fixed, no?

**Comment by egallesio** [comment]
Hello  @jpellegrini 

Happy new year.  I was  off the net for the last couple of wee, but I'm back.  Sorry for that.

About this issue, you are right: I close it.

**Comment by jpellegrini** [comment]
> Happy new year. I was off the net for the last couple of wee, but I'm back. Sorry for that.

There's nothing to be sorry about! :)
Happy New Year!
