### ISSUE TITLE
What is @l in the documentation?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#336]
What is the `@l` directive in documentation? Something like "new line"?
The first time I saw it I thought it was a typo, but now I see it being used a lot (the documentation of `call/cc` uses it five times).
It seems to be printed verbatim in the online help:

```
stklos> (help 'call/cc)
Help for call/cc:
Documentation:
  (call-with-current-continuation proc)
  (call/cc proc)
   |Proc| must be a procedure of one argument. The procedure
  ...
  when the escape procedure was created. Calling the escape procedure may cause
  the invocation of before and after thunks installed using |dynamic-wind|.
  @l
  The escape procedure accepts the same number of arguments as
  the continuation to the original call to
```

**Comment by egallesio** [comment]
Yes, it is a shortcut for `,(linebreak)` 
I have pushed a version which will delete them 
 
However, there are numerous other places where the formatting for help is not good. The bars around symbols, the `,(bold "XXX")`, ... 
 Having a good documentation would be a lot of work

**Comment by jpellegrini** [comment]
Ah, thank you!
I'll fix my documentation PR then.

As to the amount of work, we can do that little by little...

**Comment by jpellegrini** [comment]
Ok - The PR, #307 , is fixed (doesn't remove `@l` anymore).
