### ISSUE TITLE
Links to SRFIs on STklos webpage are wrong

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#348]
Hi!

It looks like the SRFI links are wrong:

`SRFI-111 — Boxes` links to `http://srfi.schemers.org/srfi-Boxes/srfi-111.html`

(The title was used instead of the SRFI number...)

Seems to be like that for all srfis listed in stklos.net.

**Comment by egallesio** [comment]
I don't know what I have done, since it is something that I have already corrected. I must have made a mistake again during a merge :disappointed: 

Anyway, this must be OK now.

**Comment by egallesio** [comment]
Thanks

**Comment by jpellegrini** [comment]
It is fixed! :)
