### ISSUE TITLE
How to implement modules that have several parts?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#35]
Is there a rpeferred way to implement modules, or SRFIs which are broken into different parts? For example, SRFI-41 has two parts, "primitive" and "derived". SRFI-159 has several submodules.

I thought that, for example, SRFI-41 could be implemented as two STklos modules, "streams-primitive" and "streams-deived", and then one third module "srfi-41" which requires the other two. Is this OK? (That would probably make it easier to implement it as R7RS modules when STklos gets the R7RS module system).
Or is some other way preferred?

**Comment by egallesio** [comment]
> I thought that, for example, SRFI-41 could be implemented as two STklos modules, "streams-primitive" and "streams-deived", and then one third module "srfi-41" which requires the other two. Is this OK?

I think this is definitvely the correct way to go. Furthermore, it permits to load only a part of the SRFI, or replace one part with a better implementation later. 

> (That would probably make it easier to implement it as R7RS modules when STklos gets the R7RS module system).
Exactly!

**Comment by jpellegrini** [comment]
Thank you!
I'll start working on SRFI-41 and, maybe, SRFI-159.
