### ISSUE TITLE
Is the `tc_not_boxed` value used at all?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#358]
Hi @egallesio !
I've been thinking about the representation of serialized objects, and found that in `stklos.h` the value `tc_not_boxed` is defined as `-1`. And it is the only negative value in the `type_cell` enum. Also,it is only used in `switch` statements in `boolean.c`:

```
grep tc_not src/*.c
src/boolean.c:    case tc_not_boxed:
src/boolean.c:    case tc_not_boxed:
src/boolean.c:    case tc_not_boxed:
```

And those cases actually test for `tc_not_boxed` and a lot of other values, but it doesn't seem that this value makes a difference.

Is it used at all, or is it from some idea that was not implemented?

**Comment by egallesio** [comment]
The value is returned by the `STYPE` macro in stklos.h  on non-boxed types (fixnums, characters, small constants, ...).   The value was set to -1, since it aggregates several values of different type, but the value doesn't really need to be -1, 0 could be fine too, if you prefer.

**Comment by jpellegrini** [comment]
> The value is returned by the `STYPE` macro in stklos.h on non-boxed types (fixnums, characters, small constants, ...). The value was set to -1, since it aggregates several values of different type, but the value doesn't really need to be -1, 0 could be fine too, if you prefer.

Ah, ok -- now I see. Thanks @egallesio !

**Comment by jpellegrini** [comment]
We don't have a user-available `type-of` procedure, do we? Not that I think it's needed, just checking. :)

**Comment by egallesio** [comment]
`class-of` has (sort-of) this role.

**Comment by jpellegrini** [comment]
Ah, right! :)
Thanks @egallesio !
I think we can close this one then.
