### ISSUE TITLE
Parallel compilation triggers issues with documentation extraction?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#360]
Hi @egallesio !

I saw the huge changes in the documentation system -- that's really great! :fireworks: 

I'm a bit slow, but making progress on the serialization and new macro ideas.

One thing: the build system seems to be triggering a problem when ran in parallel -- it is related to documentation extraction. See, with `-j10` I get this:

```
Extracting documentation from fixnum.c
**** Error while executing file "../../utils/stklos-pp.stk"
	 Where: in read
	Reason: end of file while reading a string on `#[input-port '/home/jeronimo/pkg/scheme/STklos-github/doc/DOCDB' (4)]'

  - read
  - <<let/call>>
  - #[closure 7f9703f10370]
  - <<let/call>>
  - <<let/call>>
  - read-database
  - %execute
  - #[closure 7f9703f10870]
  - %call-for-values
  - <<let/call>>
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
Extracting documentation from fport.c
```

and each time I compile it happens at a different point (this one was after `fixnum.c`; one other time I got it after  `trace.stk`, but it was the same error (end of file while reading a string on DOCDB)

**Comment by jpellegrini** [comment]
Probably not related, but I also get these warnings earlier (right after compilatoin of the C files):

```
./tmpcomp -o stklos-pp stklos-pp.stk
stklos-pp.stk:58: warning: reference to undefined symbol pp-translate
stklos-pp.stk:38: warning: reference to undefined symbol pp-parse-metadata
```

**Comment by egallesio** [comment]
Hi @jpellegrini, 

It should work now.

**Comment by jpellegrini** [comment]
Yes, it works! :fireworks: that's great!
Thanks @egallesio for the quick fix
