### ISSUE TITLE
void documentation: does it evaluate its arguments?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#361]
The docs say,

```
 * (void)
 * (void arg1 ...)
 *
 * Returns the special *_void_* object. If arguments are passed to |void|,
 * they are evalued and simply ignored.
```

But then, this happens:

```
stklos> (void (display 1) (newline))
stklos> (define x 1)
;; x
stklos> x
1
stklos> (void (set! x 2))
stklos> x
1
```

which is different from:

```
stklos> (define (f . args) #void)
;; f
stklos> (f (display 1) (newline))
1
stklos> (f (set! x 2))
stklos> x
2
```

So... Why doesn't `void` evaluate its arguments?

**Comment by jpellegrini** [comment]
It seems to be the `_UNUSED` macro...

I have tried removing it and using this instead:

```
DEFINE_PRIMITIVE("void", scheme_void, vsubr, (int argc, SCM *argv))
{
    (void) argc;
    (void) argv;
    return STk_void;
}
```

which does silence GCC's warnings about unused arguments, but still, `void` doesn't evaluate its arguments.

**Comment by egallesio** [comment]
It should be OK now. The problem was that the function call to void  was inlined as the constant `#void ` (and the parameters were not evaluated at all).

**Comment by jpellegrini** [comment]
Yes, it works now - that was fast! :)

BTW - I'll still be somewhat slow to do things in the next weeks, but I didn't give up.

**Comment by egallesio** [comment]
> BTW - I'll still be somewhat slow to do things in the next weeks,
No problem. Maybe it will allow me to catch up on the PRs that are not merged :wink: 
> but I didn't give up.
I'm sure of that.
