### ISSUE TITLE
`in-module` looks in current (or STklos) module when the symbol is not found in the requested module?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#381]
Hi @egallesio 

What happens here?
```
stklos> (define-struct st a b)
;; st
stklos> (describe st)
#[struct-type st 140043913718656] is a structure type whose name is st.
Parent structure type: #f
Slots are:
	a
	b
stklos> (define-module a (export st) (define st (lambda () -10)))
;; a
stklos> st
#[struct-type st 140043913718656]
stklos> (import a)
stklos> st
#[closure st]
stklos> (st)
-10
stklos> (in-module STklos st)
#[closure st]
stklos> ((in-module STklos st))
-10
stklos> (in-module SCHEME st)
#[closure st]
stklos> ((in-module SCHEME st))
-10
stklos> (member 'st (module-symbols (find-module 'SCHEME)))
#f
```
So... The `(in-module SCHEME st)` should probably not have found the `st` symbol. Or did I get something wrong?

**Comment by egallesio** [comment]
Hi @jpellegrini,

This is normal: the SCHEME module is a module (not a R7RS library), and as a consequence, it inherits from the module STklos (perhaps, this should be changed, but this is how it is implemented now).  The `in-module` form shows you the value you'll see when you are in the module (that is, when you have selected the module).

You should have:

```scheme
stklos> (define-struct st a b)
;; st
stklos> (define-module a (export st) (define st (lambda () -10)))
;; a
stklos> (list (in-module STklos st) (in-module a st) (in-module SCHEME st))
(#[struct-type st 140249308774400] #[closure st] #[struct-type st 140249308774400])
stklos> (import a)
stklos> (select-module SCHEME)
SCHEME> st
#[closure st]
SCHEME> (select-module a)
a> st
#[closure st]
a> (select-module STklos)
stklos> st
#[closure st]
stklos> (list (in-module STklos st) (in-module a st) (in-module SCHEME st))
(#[closure st] #[closure st] #[closure st])
stklos>
```

In fact in the SCHEME module, you should see that the `st` binding is associated to the value the one that is available in STklos, that is, after the import, to the closure of module `a`. The structure, will be GCed.

> So... The (in-module SCHEME st) should probably not have found the st symbol. Or did I get something wrong?

Use the `symbol-value` function to find the value of a symbol in the associated module hash-table. (and `symbol-value*` to see its value in the given hash-table AND in the STklos module (if we are not in a library)).

```scheme
stklos> (symbol-value 'st (find-module 'SCHEME) 'absent)
absent
stklos> (symbol-value* 'st (find-module 'SCHEME) 'absent)
#[closure st]
stklos> 
```

In fact, in module is a simple macro thats uses `symbol-value*`

**Comment by jpellegrini** [comment]
Ok @egallesio sorry - I misinterpreted how it works, thanks for the explanation! I'm closing this.
