### ISSUE TITLE
Text typed into REPL can be almost invisible

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#4]
Are you hard-coding a blue or black color for text typed into the REPL when running `stklos` from a terminal? That color is almost invisible on the terminal emulators I use (in general, blue and black text colors are notorious for causing problems on many terminals).

All of the other text (prompt, errors, evaluation results) is clearly visible. The banner (the text with version and copyright at the start) is also quite easy to read.

**Comment by egallesio** [comment]
Yes things are mostly hard coded for the REPL. It is on my todo list to have something more configurable. The only solution I see is a variable that could be defined in the rc file, but I'm not completely fan of that (my terminals are mostly dark but remote ones are generally light), and a set of colors for one kind of terminal is not suitable for the other one. 
The thing is that it seems difficult, in a sure manner, to query the background color of a terminal to determine a set of colors. If you have any idea...

**Comment by jpellegrini** [comment]
What about creating some procedures for changing the colors? Then the user could change the colors dynamically, or even call the procedures in `stklosrc`. If you need different colors in different hosts, it would be possible to query environment variables in those hosts and set the colors accordingly.

**Comment by lassik** [comment]
I'd recommend some mechanism other than environment variables, As most people already have a big list of different envars and it's not easy to write anything complex in there.

Perhaps an `init.scm` file in the home directory somewhere? That file could call Scheme procedures to set the colors.

Recent versions of Mac applications detect whether the OS is set to a "dark" or "light" theme and do interesting things to change their appearance automatically. I don't know if anyone is advocating a standard dark/light setting for terminals, or whether that kind of setting would solve this problem.

**Comment by lassik** [comment]
Though there's still the problem that one person can use multiple terminal themes on the same computer. It can make it easier to pay attention to different windows if they are different colors.

Almost all command-line programs I have work fine quite well with any terminal theme, but they usually do it by using extremely simple colors.

In principle, ANSI color theming is supposed to be the solution to this problem, but I guess not all themes follow clear rules about contrasting colors.

**Comment by jpellegrini** [comment]
> I'd recommend some mechanism other than environment variables, As most people already have a big list of different envars and it's not easy to write anything complex in there.

Yes -- env vars was just one example -- I'd check `$HOSTNAME` and decide what color to use. A silly example:

```
(let ((host (getenv "HOSTNAME")))
  (if (string= host "some-computer")
      (set-repl-background (color 'white))))
```

But I could have used `(hostname)`, or maybe a command line option, read via `(argv)`.
STklos would only offer the colorsetting procedure. It already has `getenv`, `hostname` and `argv`.

> Perhaps an `init.scm` file in the home directory somewhere? That file could call Scheme procedures to set the colors.

But there is `stklosrc` already... That's exactly what I meant -- set the colors in a Scheme init file.
The only thing STklos would do is to provide color-setting procedures. Like the following, perhaps?

```
(color "some-ANSI-color-sequence")
(color 'some-color-name)

(set-repl-background-color ...)
(set-repl-foreground-color ...)
(set-repl-error-color  ...)
```

**Comment by jpellegrini** [comment]
> Though there's still the problem that one person can use multiple terminal themes on the same computer. It can make it easier to pay attention to different windows if they are different colors.

Yes. And the user could enter STklos and, in each REPL, set a different theme:

```
(set-repl-theme 'solar)
```

`set-repl-theme` would be a user procedure, built on top of `set-repl-background` and other similar procedures.

> Almost all command-line programs I have work fine quite well with any terminal theme, but they usually do it by using extremely simple colors.

Which would be possible by using a simple theme (black+white, for example)

> In principle, ANSI color theming is supposed to be the solution to this problem, but I guess not all themes follow clear rules about contrasting colors.

If the user could build her own themes, and some interesting pre-built themes were offered, wouldn't it be ok?

**Comment by lassik** [comment]
All of that sounds good. I didn't know there's already a `stklosrc`.

Maybe there should be no colors by default (i.e. the text would be standard white-on-black or black-on-white), but custom Scheme procedures to set them if you want to.

**Comment by egallesio** [comment]
I've added a theme system for the REPL. I'll try to commit it later today.

**Comment by jpellegrini** [comment]
I had also noticed we can get a black and white REPL bu calling
```
stklos -i
```

or by doing this:

```
(parameterize ((repl-prompt-use-color? #f)) (repl))
```

But a themable REPL is really a great thing, much better!

**Comment by lassik** [comment]
Great. Thank you for responding to feedback @egallesio!

**Comment by egallesio** [comment]
I have committed a patch to allow the customization of console colors

The parameter new function `repl-theme` returns the list of color associations currently in use.
 
To change the REPL theme, you can just use
   - `(repl-theme 'xxx)` where xxx is one of `classic`, `monochrome`or ` minimal`
   - `(rep-theme '(:error red :prompt (bold red) ...))` to fix a   personal theme

To change only one color in the current theme, you can do
      `(key-set! (repl-theme) :prompt '(bold green))`

Prompt theme/colors can be changed interactively but a a good place to change your theme is the .stklosrc file.

**Comment by egallesio** [comment]
BTW, the default theme is classic (nearly the same as before, but it should avoid the problem you had @lassik. Tell me if this is not the case and I'll change the default values of the classic theme.

**Comment by lassik** [comment]
Just compiled and tried the latest. Great work, the `repl-theme` command is very nice! And yes, the problem of invisible REPL input is solved in the default theme.
