### ISSUE TITLE
`lseq.stk` and `ilist.c` are missing

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#421]
Hi @egallesio !
I think you forgot to commit `lseq.stk`

(Sorry I'm on mobile, will get back later)

**Comment by jpellegrini** [comment]
And `ilist.c` also...

These seem to be all missing files -- after `touch lib/scheme/ilist.c lib/scheme/lseq.stk`, STklos only complains later when it tries to compile `116.stk` and `127.stk` (which would use `lseq.c` and `ilist.c`. But other than that, everything seems to be ok.

**Comment by egallesio** [comment]
Hi @jpellegrini,

Thanks for your continuaous help. This should be OK now.

**Comment by jpellegrini** [comment]
It's fixed! I forgot to close the issue...
