### ISSUE TITLE
endian.h

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#431]
```
clang -g -O2  -fPIC -fno-common -I../../src -I/usr/local/Cellar/bdw-gc/8.2.2/include  -c -o bytevector.o bytevector.c
bytevector.c:29:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
```

`endian.h` does not exist on Mac.

**Comment by lassik** [comment]
Portable solutions: https://github.com/cpredef/predef/blob/master/Endianness.md

**Comment by egallesio** [comment]
Hi @lassik,
I have suppressed the inclusion of  `endian.h`, since the endianness seems to be dynamically computed in this file. 

To @jpellegrini: Am I right here?

**Comment by jpellegrini** [comment]
> I have suppressed the inclusion of `endian.h`, since the endianness seems to be dynamically computed in this file.
> 
> To @jpellegrini: Am I right here?

Yes, if is determined dynamically in `bytevector_init_native_endianness`.

**Comment by egallesio** [comment]
Thanks, @jpellegrini, for your (fast) response.

**Comment by lassik** [comment]
With the latest master, I'm still getting a build failure on Mac. It's missing `le32toh()` and other similar functions/macros.

Here's [a portable version of `endian.h`](https://github.com/mikepb/endian.h) that could perhaps solve the problem. It's a simple file of public domain code.

**Comment by egallesio** [comment]
Oops. You are correct (didn't see the conversion functions). For some reason, the compilers on Linux don't help, since they don't emit a warning when these functions are used. The functions are now in glibc, but their usage without including `<endian.h>` should produce a warning (or is it indirectly included, but I have not seen how).

Thanks a lot for the link. I'll use it to fix this issue.

**Comment by egallesio** [comment]
I have pushed a commit which uses the portable version of endian.h that you pointed me. Tell me if it is OK for you now. 
Happy new year eve.

**Comment by lassik** [comment]
Thanks! It builds for me now :)

Happy new year!
