### ISSUE TITLE
Comparison of stklos-config and "stklos -V"

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#435]
The following `stklos-config` flags have equivalent `stklos -V` output:

```
[--prefix | -p]         Prefix that was given during the build

(install-dir "/Users/lassi/.local/stow/stklos-head")
```

```
[--version | -v]        Version of STklos that is installed

(version "1.70")
```

```
[--threads | -t ]       Display the name of the valiable thread system

(stklos.threads pthread)
```

```
[--libraries |-L ]      Display a summary of used and compiled libraries

(stklos.system-libs libffi libpcre libgmp libgc)
(stklos.compiled-libs)
(build.configure "--prefix=/path/to/..." "CC=gcc" "CFLAGS=-g -O2")
```

These flags would be covered by `c.compile` and `c.link` in SRI 176:

```
[--cc]                  CC used for building STKlos
[--cflags]              CFLAGS used for building STklos
[--ldflags]             LDFLAGS used for building STklos
```

These flags don't yet have equivalent properties in SRFI 176:

```
[--compile | -c]        Command that should be run to compile
                        shared libraries.
[--link | -l]           Command that should be used to link shared
                        libraries
[--shared-suffix | -s]  Suffix for shared libraries on current
                        platform
```

**Comment by egallesio** [comment]
Hi @lassik,
I have reported the values of `stklos-config` in SRFI-176 properties. We have now:

```sh
$ stklos -V | grep '(c\.'
(c.version "gcc (GCC) 12.2.0")
(c.compile "gcc" "-O2" "-Wall" "-Wextra" "-DSTK_DEBUG" "-g" "-rdynamic")
(c.link "gcc" "-lgmp" "-lpcre" "-lpcreposix" "-lffi" "-lgc" "-lpthread" "-ldl" "-lm")
(c.type-bits (char 8) (short 16) (int 32) (long 64) (float 32) (double 64) (pointer 64))
```


About the `stklos-config` flags absent of the properties, I have added them to the `stklos.shlib` prefix, since it is STklos specific.

```sh
$ stklos -V | grep '(stklos.shlib'
(stklos.shlib.compile "gcc" "-fpic" "-nostdlib" "-I/usr/local/STklos/include/stklos" "-I/usr/local/STklos/include/stklos/gc")
(stklos.shlib.lib "ld" "-shared")
(stklos.shlib.suffix "so")
```

**Comment by lassik** [comment]
Thank you very much for adding these! Looks good.

The shared library properties would probably be useful for other C-based Scheme implementations as well. Even though the SRFI is finalized, we can add new properties to [the registry](https://registry.scheme.org/#version-properties). How would this look?

```Scheme
(c.library.compile "gcc" "-fPIC" "-fno-common" "-I/Users/lassi/.local/stow/stklos-head/include/stklos" "-I/Users/lassi/.local/stow/stklos-head/include/stklos/gc")
(c.library.link "gcc" "-bundle" "-flat_namespace" "-undefined" "suppress")
(c.library.extension ".dylib")
```

Notes on the details:

* Even though C has both statically linked libraries and shared libraries, it's unlikely that the user of a Scheme implementation will build their own static libraries without also rebuilding the Scheme implementation. Therefore "library" should be unambiguous enough?
* "Extension" is probably a more common word than "suffix" when talking about file names, especially on Windows.
* Including the dot in the extension maybe wise since there could some some OS or use cases where the extension is blank? In that case, `(c.library.extension "")` would express that.

We could also add `scheme.srfi.count` based on `stklos.srfi.count`.

And threads is used by both STklos and Gauche:

```
(stklos.threads pthread)
(gauche.threads pthreads)
```

We could add a standard property for that. Maybe just `(threads pthreads)`?

BTW the spelling currently differs: `stklos -V`calls it `pthread` (singular) whereas `stklos-config -t` calls it `pthreads` (plural).

**Comment by lassik** [comment]
> * "Extension" is probably a more common word than "suffix" when talking about file names, especially on Windows.
> * Including the dot in the extension maybe wise [...]

Prior art from Chez Scheme:

```
> (library-extensions)
((".chezscheme.sls" . ".chezscheme.so")
  (".ss" . ".so")
  (".sls" . ".so")
  (".scm" . ".so")
  (".sch" . ".so"))
```

**Comment by egallesio** [comment]
I think I have implemented all your suggestions.

About the library extension, it is now `".so"` instead of `".dylib"` on MacOs, because it is the extension used by STklos for Scheme/C libraries on this system. MacOs is the only system I know that distinguish library and dynamically loadable compiled code. 

BTW, when looking at this issue, I was not able to access to line editing on MacOs and to symbol completion. Is it also the case for you? In fact, I have no more access to a Mac, and I have made my tests in a freshly installed VM. If it works for you, can you tell me if you set a SHELL variable or something else for that. It used to work before, and as far as I can remember, I didn't do anything to make it work. 
On my VM, I have `/usr/lib/libreadline.dylib` which is present, but for some reason, STklos doesn't see it :disappointed:

**Comment by lassik** [comment]
> I think I have implemented all your suggestions.

Thank you vey much!

> About the library extension, it is now `".so"` instead of `".dylib"` on MacOs, because it is the extension used by STklos for Scheme/C libraries on this system. MacOs is the only system I know that distinguish library and dynamically loadable compiled code.

Fair enough. I don't even understand the distinction :)

> BTW, when looking at this issue, I was not able to access to line editing on MacOs and to symbol completion. Is it also the case for you? In fact, I have no more access to a Mac, and I have made my tests in a freshly installed VM. If it works for you, can you tell me if you set a SHELL variable or something else for that. It used to work before, and as far as I can remember, I didn't do anything to make it work. On my VM, I have `/usr/lib/libreadline.dylib` which is present, but for some reason, STklos doesn't see it 😞

Line editing has stopped working on my Mac too. It seems the OS no longer ships GNU readline due to licensing issues. Instead, it ships the BSD editline library (libedit) with a `readline.h` emulation layer.

The original GNU readline can be installed from 3rd party package manager like Homebrew or MacPorts.

**Comment by lassik** [comment]
I also have `/usr/lib/libreadline.dylib`. It's a symbolic link to `libedit.3.dylib`.

**Comment by lassik** [comment]
I added the new properties to the [table at the Scheme Registry](https://registry.scheme.org/#version-properties).

**Comment by egallesio** [comment]
> Line editing has stopped working on my Mac too. It seems the OS no longer ships GNU readline due to licensing issues. Instead, it ships the BSD editline library (libedit) with a readline.h emulation layer.

> The original GNU readline can be installed from 3rd party package manager like Homebrew or MacPorts.

I had installed `libedit` and `readline` and it doesn't work anymore. The problem is that the line editing library is not linked (statically or dynamically) to STklos executable; it is STklos REPL which try to find this library at runtime and extract the functions it needs using FFI. It used to work, but now, even if libraries are present, they are not found on MacOS. 

I'll try to understand why it doesn't work anymore. Thanks @lassik for the infomation.

**Comment by lassik** [comment]
PR #438 is also related to this issue.

**Comment by egallesio** [comment]
I've found the problem about line editing on macOS: it seems that their current `libedit` library has changed and do not provide anymore some functions (they are only used for integrating `readline` in an event loop). It should be OK now. 

Going to look at PR #438. Thanks.

**Comment by lassik** [comment]
> I've found the problem about line editing on macOS:

Your commit solves the problem on my mac too. Thanks!
