### ISSUE TITLE
library-list and library-exports

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#437]
Would it be possible to add two procedures, `library-list` and `library-exports`, which work as in Chez Scheme:

```Scheme
> (library-list)
((rnrs) (chezscheme) (scheme) (rnrs conditions) (rnrs files)
 (rnrs base) (rnrs syntax-case) (rnrs exceptions)
 (rnrs lists) (rnrs bytevectors) (rnrs control)
 (rnrs unicode) (rnrs enums) (rnrs r5rs) (rnrs eval)
 (rnrs hashtables) (rnrs sorting) (rnrs programs)
 (rnrs mutable-pairs) (rnrs mutable-strings) (rnrs io ports)
 (rnrs io simple) (rnrs arithmetic flonums)
 (rnrs arithmetic bitwise) (rnrs arithmetic fixnums)
 (rnrs records syntactic) (rnrs records procedural)
 (rnrs records inspection) (chezscheme csv7) (scheme csv7))

> (library-exports '(rnrs lists))
(assoc assp assq assv cons* exists filter find fold-left
  fold-right for-all member memp memq memv partition remove
  remp remq remv)
```

This is quite convenient for exploring the system IMHO.

Notes on `library-list`:

* It lists all libraries that have been loaded.
* It also lists libraries that have not been imported into the caller's environment.
* It does not list all libraries that could be loaded from the file system.

**Comment by jpellegrini** [comment]
In STklos, a library are a particular type of module, and there is `all-modules`:

```
stklos> (all-modules)
(#[module scheme/write] #[module scheme/base] #[module REPL-READLINE] #[module READLINE] #[module REPL] #[module SRFI-0] #[module MBE] #[module STKLOS-OBJECT] #[module STKLOS-COMPILER] #[module SCHEME] #[module stklos])
```

So I suppose that adding `library-list` would be as trivial as 
```
stklos> (define-library a)
;; a
stklos> (filter library? (all-modules))
(#[library (a)])
```

*However*, many (most?) SRFIs are implemented as modules, and not as R7RS libraries...
```
stklos> (import (srfi 43))
stklos> (filter library? (all-modules))
(#[library (a)])
```

**Comment by jpellegrini** [comment]
As to `library-exports`, guess what?  :grin: There is  `module-exports`:

```
stklos> (module-exports (find-module 'scheme/base))
((zero? . zero?) (write-u8 . write-u8)  ... (+ . +) (* . *))
```

**Comment by jpellegrini** [comment]
> In STklos, a library are a particular type of module

Sorry, I should have explained the difference.

In a module, all the bindings in the `STklos` module are visible. Not in a library.

```
stklos> (define-module a (export d) (define d display))
;; a
stklos> (in-module a d)
#[primitive display]
stklos> (define-library a (export d) (begin (define d display)))
**** Error:
%execute: variable `display' unbound
```

(Also, the syntax of a library is stricter -- as per the standard, a `begin` is required.)

**Comment by lassik** [comment]
Neat!

Is there a fundamental reason why modules are distinct from libraries, or just for historical reasons?

**Comment by jpellegrini** [comment]
@lassik STklos used to have modules only, and libraries were added recently for compliance with R7RS.

**Comment by jpellegrini** [comment]
* one thing:  a libray _**is**_ a module:

```
stklos> (define-library a (begin))
;; a
stklos> (find-module 'a)
#[library (a)]
stklos> (module? (find-module 'a))
#t
```

The C code that deals with modules and libraries is in [`src/env.c`](https://github.com/egallesio/STklos/blob/master/src/env.c) and some library-only parts are in [`src/lib.c`](https://github.com/egallesio/STklos/blob/master/src/lib.c)
The Scheme code is in [`lib/module.stk`](https://github.com/egallesio/STklos/blob/master/lib/module.stk) and [`lib/library.stk`](https://github.com/egallesio/STklos/blob/master/lib/library.stk)

**Comment by egallesio** [comment]
Thanks @jpellegrini for your explanation. 
STklos offers modules since its first version (at the R4RS era). The interaction between modules and libraries needs to be documented (it is on my TODO list). Furthermore, the documentation needs to be adapted, since some points are no more true. I'll try to do that in a very near future. 
I'll also add `library-list` and `library-exports`, since they are easy to implement.

**Comment by egallesio** [comment]
This is now implemented. Note that `library-list` returns a list of library objects (and not a list of names), since libraries are first class objects in STklos.
