### ISSUE TITLE
PRs for 2.0

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#450]
Hi @egallesio !
I see you're preparing 2.0 :fireworks: 

Maybe you could consider for 2.0 -- besides those by @Zambito1 -- the PRs  #444 #443 and #304 ?

**Comment by jpellegrini** [comment]
I wasn't quick enough. You just merged #444 :smile:

**Comment by egallesio** [comment]
I'll merge of course these PRs (and some more).  For now, I have deleted support for ScmPkg, since packages are not really used/maintained.  2.0 is not really for tomorrow.

**Comment by egallesio** [comment]
Finally, we can close this issue. :tada:
