### ISSUE TITLE
Is SPARC still supported?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#457]
I just found this in `vm.c`...

```c
#ifdef sparc
#  define FLUSH_REGISTERS_WINDOW()      asm("t 0x3") /* Stolen in Elk 2.0 source */
#else
#  define FLUSH_REGISTERS_WINDOW()
#endif
```

**Comment by lassik** [comment]
QEmu still comes with `qemu-system-sparc` and `qemu-system-sparc64` in case someone is feeling adventurous :)

64-bit ARM is starting to look like the dominant architecture of the next 20 years.

**Comment by jpellegrini** [comment]
Ok, sorry about the noise then! :)
Closing...
