### ISSUE TITLE
(R7RS) current-{output,input,error}-port should be  parameter objects

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#46]
Hello,

According to R7RS, `current-output-port` should be a parameter object, so this:

```
(define f (open-output-file "oo"))
(parameterize ((current-output-port f)) (display "hey"))
(close-output-port f)
```

should write `"hey"` to the file `"oo"`. But STklos does not let me do that:

```
stklos> (define f (open-output-file "oo"))
;; f
stklos> (parameterize ((current-output-port f)) (display "hey"))
**** Error:
%parameter-dynenv-pop!: bad parameter `#[primitive current-output-port]'
	(type ",help" for more information)
```

I see that these are implemented as primitives in `port.c`.

Anyway -- the current  STklos documentation on `current-output-port` says it returns the current output port, and doesn't mention parameterize, but it is listed with an argument "`obj'" in the documentation (but it will refuse taking an argument).

**Comment by egallesio** [comment]
I'm aware of this problem and my first attempts to transform these functions in parameters was a fail. If I remember, I had problems with the integration with threads, as well as  the way they are  actually implemented). 

It is on my TODO list, but keeping it in this list of issues will force me to finish the work.

**Comment by lassik** [comment]
Are there general difficulties with parameters in the presence of threads, or just with the current-*-port parameters?

**Comment by egallesio** [comment]
It should be OK now.

**Comment by jpellegrini** [comment]
I suppose we can close this... I have tested `current-output-port` with `parameterize` and also as `(current-output-port some-port)`, and it works fine. Same for error/input.
