### ISSUE TITLE
Use of the term "informations"

### ISSUE THREAD

**Issue by ryandesign** [egallesio/STklos#492]
I see several occurrences of the word "informations" in the code. "Information" is a [mass noun](https://en.wikipedia.org/wiki/Mass_noun) in English so it is always written as "information." You can have "one piece of information" or "two pieces of information" but there are never "informations".

**Comment by egallesio** [comment]
Got it. It's hard for a French guy to not use it in a plural form, since it is used in this form perhaps 80% of the time in French.  
Added a TODO item to correct the ones which are user visible. 

Thanks @ryandesign

**Comment by ryandesign** [comment]
In German too! What can I say. English is weird.

**Comment by ryandesign** [comment]
"Performance" is another one of those terms. When speaking about the speed or efficiency of an algorithm, for example, you'll always talk about "performance", never "performances."

There's another sense of the term "performance" that probably won't come up in STklos which is pluralized normally, and that's to do with musical concerts, stage plays, and other entertainment. For example, you could say, "Last year we attended several symphony performances."

**Comment by egallesio** [comment]
I think that all occurrences of  performance and information are now corrected. 
Thanks  for signaling this issue.
