### ISSUE TITLE
Switch to pcre2

### ISSUE THREAD

**Issue by ryandesign** [egallesio/STklos#499]
I'm not sure how big a project this would be but I see STklos bundles pcre 8.45, or can use an external pcre, but according to the [pcre homepage](https://www.pcre.org):

> There are two major versions of the PCRE library. The current version, PCRE2, released in 2015, is now at version 10.39.
>
> The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. This version of PCRE is now at end of life, and is no longer being actively maintained. Version 8.45 is expected to be the final release of the older PCRE library, and new projects should use PCRE2 instead.

So it might be good to switch to using pcre2 instead.

**Comment by jpellegrini** [comment]
It wold be nice to have PCRE2. But it seems like a big project:
https://stackoverflow.com/questions/70273084/regex-differences-between-pcre-and-pcre2

**Comment by egallesio** [comment]
In fact, STklos uses only the POSIX interface for regexps. So it should not be too hard (not really looked at it) to use another version, or another regexp library with POSIX compatibility. It's on my TODO list (but post v2.0)

**Comment by egallesio** [comment]
> So it might be good to switch to using pcre2 instead.

Done. The embedded version is 10.42.
