### ISSUE TITLE
R7RS define-library support

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#5]
I see you have quite a few R7RS features already. That's great! Do you plan to support `(define-library ...)` eventually? If so, I can volunteer to be a beta tester.

The de facto standard for R7RS libraries is to put the `(define-library ...)` form in `foo.sld` and the library implementation in `foo.scm`. The `define-library` contains `(include "foo.scm")` to load the implementation. `cond-expand` is also often used inside `define-library` but you have that already :)

**Comment by lassik** [comment]
Also SRFIs are imported like `(import (srfi 123))` so the library name can contain numbers. Many R7RS implementations load `(srfi 123)` from `x/srfi/123.sld` where `x` is any directory in the import path.

**Comment by egallesio** [comment]
> I see you have quite a few R7RS features already. That's great! Do you plan to support `(define-library ...)` eventually? If so, I can volunteer to be a beta tester.
> 
> The de facto standard for R7RS libraries is to put the `(define-library ...)` form in `foo.sld` and the library implementation in `foo.scm`. The `define-library` contains `(include "foo.scm")` to load the implementation. `cond-expand` is also often used inside `define-library` but you have that already :)

Ouch. I missed that message. Yes I plan to have define-library. I have started to implement and try to finish it asap. Some points are not easy to implement with what is already existing (rename clauses for instance). 
Glad to see that you could be a beta tester :-)

**Comment by lassik** [comment]
Awesome news!! Good luck with the implementation. There are quite a lot of intricacies.
