### ISSUE TITLE
Inconsistency between manpage and README

### ISSUE THREAD

**Issue by ryandesign** [egallesio/STklos#508]
The manpage says:

https://github.com/egallesio/STklos/blob/590c727038b2790ff047008035072f031eb399d3/doc/stklos.1.in#L26-L27

but the README says:

https://github.com/egallesio/STklos/blob/590c727038b2790ff047008035072f031eb399d3/README.md?plain=1#L11-L12

The README changed from mentioning R5RS to mentioning R7RS in 02a3e1d640f26243fb74e83bd4bda3612312badc. Should the manpage be changed as well?

**Comment by jpellegrini** [comment]
STklos is R7RS today. I think @egallesio forgot to change the manpage...

**Comment by lassik** [comment]
FYI there is now https://man.scheme.org/stklos.1

**Comment by egallesio** [comment]
Great !!!
Thanks @lassik, for the information.
This is the man page for the stable version? 
*I ask because there are new options which are not present*

**Comment by lassik** [comment]
Yes, it is for the latest stable version. I can update it when the next STklos release comes out.

https://man.scheme.org/ has many other pages too. In particular, manpages for many Scheme procedures are provided by https://github.com/schemedoc/manpages.

**Comment by jpellegrini** [comment]
@egallesio - why not stabilize for a 1.80 version, just so there is an update... ?
