### ISSUE TITLE
Makefile(s) missing dependencies on boot.img

### ISSUE THREAD

**Issue by ryandesign** [egallesio/STklos#514]
boot.img was removed from git in edd2a19b3d7293805589d7de5663fde02dccde5c.

If it doesn't exist yet at the time that tmpcomp is run, this error occurs:

```
./tmpcomp: line 83: ../../../../src/stklos: No such file or directory
```

I can fix that part of tmpcomp so that it does not rely on boot.img to find the top directory (#513) but the rest of tmpcomp also relies on boot.img and fails if it isn't there:

```
cannot boot with "/Volumes/Shared/STklos/src/boot.img" file (code=-1)
```

So the problem is that the Makefile targets that require boot.img need to declare that.

**Comment by egallesio** [comment]
The way the boot file is used has been changed and `boot.img` and the issue is (normally) gone with this change. 
Thanks @ryandesign for signaling the issue.
