### ISSUE TITLE
implicit declaration of function 'clock_gettime'

### ISSUE THREAD

**Issue by ryandesign** [egallesio/STklos#519]
stklos 1.70 and git master fail to build on older versions of macOS:

```
system.c:1485:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
  clock_gettime(CLOCK_REALTIME, &now);
  ^
system.c:1485:17: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime(CLOCK_REALTIME, &now);
                ^
system.c:1498:17: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime(CLOCK_REALTIME, &now);
                ^
1 warning and 2 errors generated.
make[2]: *** [system.o] Error 1
```

Here is a full build log from OS X 10.11: https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/214665/steps/install-port/logs/stdio

Can system.c survive without `clock_gettime`? If so, you probably want a configure test to check if it exists before you use it in system.c and elsewhere.

**Comment by jpellegrini** [comment]
I wonder why it fails... `glock_gettime` is POSIX since 2001, and its declaration should be in `time.h`, which `system.c` includes. (?)

**Comment by ryandesign** [comment]
macOS 10.12 (2016) is the earliest version of macOS that includes `clock_gettime`.

**Comment by lassik** [comment]
@ryandesign  Does pre-10.12 have some equivalent of `CLOCK_MONOTONIC`?

`CLOCK_REALTIME` is basically the layman's notion of "current time", right?

**Comment by ryandesign** [comment]
MacPorts has a "[legacy support](https://github.com/macports/macports-legacy-support)" library that backports functions available in newer operating systems like `clock_gettime` to older OS versions. I can include that library in the STklos ports to probably fix the problem, but that only helps users installing STklos via MacPorts, not those building from source or other methods.

You could include compatibility implementations of such functions in the STklos codebase and use them when the OS doesn't have them. MacPorts legacy support is open source but each function seems to have its own origin with its own license so if you wanted to copy it you'd have to evaluate whether its license is compatible. Here's the code for [`clock_gettime`](https://github.com/macports/macports-legacy-support/blob/master/src/time.c). See also a [pull request](https://github.com/macports/macports-legacy-support/pull/52) for an improvement to it.

**Comment by lassik** [comment]
Looks like good code under te ISC license. Maybe it should be added to the [SRFI 170 repo](https://github.com/scheme-requests-for-implementation/srfi-170) where others would find it as well.
