### ISSUE TITLE
Broken links in STklos website

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#53]
In the Screeshots/GUI page, there is the sentence "_This model is described in the JFP and ISOTAS papers_."
Both links are broken.

**Comment by jpellegrini** [comment]
And also in the code/explanation page, where the same links are presented again.

**Comment by egallesio** [comment]
I don't understand. It is OK for me. The URLs for the  3 links are
1. http://www.stklos.net/~eg/Publis/jfp03.pdf
2. http://www.stklos.net/~eg/Publis/Isotas96.pdf
3. https://www.stklos.net/stklos-gtklos.html

Can you test again please?

**Comment by jpellegrini** [comment]
Hi,
From the two first links I get a 404 page...
The third works.

**Comment by jpellegrini** [comment]
> And also in the code/explanation page, where the same links are presented again.

I did not mean the link to that page; I meant the link to the papers, which also appear in that page.

**Comment by egallesio** [comment]
Weird! Anyway, the 2 first links uses http. Is it OK if you use https? 
Normally it should be identical (it is for me)!

**Comment by egallesio** [comment]
My firefox rewrites http link in https. I'll change all the links in https

**Comment by jpellegrini** [comment]
> Weird! Anyway, the 2 first links uses http. Is it OK if you use https?
> Normally it should be identical (it is for me)!

Aha! That's it.   It only works with https.

**Comment by egallesio** [comment]
OK. I have updated the web site. It should be OK now. 
It seems, I'll have to look at my NGINX configuration !!!

**Comment by jpellegrini** [comment]
It's fixed!
