### ISSUE TITLE
Can't load libraries

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#536]
For some reason, STklos is not anymore completing symbol names. It was in commit 9d855f821f55.

**Comment by lassik** [comment]
Is that under Linux?

IIRC the logic for finding the readline C library changed recently. @egallesio

**Comment by jpellegrini** [comment]
```
$ ll /usr/local/lib/stklos/1.70/
total 20
-rw-r--r-- 1 root root 19704 Apr 12 10:03 readline-complete.so
drwxr-xr-x 1 root root    92 Apr 12 10:03 scheme
drwxr-xr-x 1 root root    62 Apr 12 10:03 srfi
drwxr-xr-x 1 root root    16 Apr 12 10:03 stklos
```

Hm, it's the only `.so` file in that place (clean install, after removing `/usr/local/lib/stklos` and `/usr/local/share/stklos`)

**Comment by jpellegrini** [comment]
Oooooh  I think I found it.

```
READLINE> (load-path)
("." "/home/jeronimo/.stklos/pkg/lib" "/home/jeronimo/.stklos/ext" "/usr/local/lib/stklos/1.70.1116" "/usr/local/share/stklos/1.70.1116")
```

However, that directory doesn't exist! It stil linstalls everything under `/usr/local/lib/stklos/1.70`.

**Comment by jpellegrini** [comment]
```
stklos> (import (srfi 25))
**** Error:
load: cannot load file "srfi/25"
```

**Comment by jpellegrini** [comment]
@egallesio -- a question: STklos should install under which directory?

```
/usr/local/{share,lib}/stklos/major.minor.PATCH
/usr/local/{share,lib}/stklos/major.minor
```

**Comment by egallesio** [comment]
Oops. My fault.
I have changed the way versions number are managed and forgot to test where things are installed. I correct that asap.
Sorry.

**Comment by egallesio** [comment]
This should be OK now. 

> @egallesio -- a question: STklos should install under which directory?
> 
> ```
> /usr/local/{share,lib}/stklos/major.minor.PATCH
> /usr/local/{share,lib}/stklos/major.minor
> ```

IMO,  `/usr/local/{share,lib}/stklos/major.minor` avoids cluttering `/usr/local`.

**Comment by jpellegrini** [comment]
> IMO, `/usr/local/{share,lib}/stklos/major.minor` avoids cluttering `/usr/local`.

I agree! :)

So it looks like this one is fixed! :smiley:
