### ISSUE TITLE
When the imaginary part of a number is `+inf.0`, STklos prints an extra `+` sign -- for example, `+inf.0++inf.0i`

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#563]
Hi @egallesio !

```
stklos>  (* 1+1i +inf.0)
+inf.0++inf.0i

stklos> (* 0+1i +inf.0)
-nan.0++inf.0i

stklos>  (* 2+1i +inf.0)
+inf.0++inf.0i
```
Oops... Looks like there's an extra `+` being printed there...

**Comment by egallesio** [comment]
This one was also in my TODO list. I see that you have already corrected it. Great! Thanks a lot, @jpellegrini 
I have some comments in the PR itself.
