### ISSUE TITLE
build: `cannot load file "stklos/preproc"`

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#572]
Hi @egallesio !
This is strange. I have the exact same checkout (b824f7e49460767a228624f3f7e78ae1eb74df09) in two different machines, and STklos compiles on one, but not on the other.

This is the error that shows up (when building the documentation):
```
make[2]: Entering directory '/home/jeronimo/pkg/scheme/STklos/doc/pp'
../../src/stklos -q -I ../../lib -f ../../utils/stklos-pp.stk -- -D "doc-fmt: 'html" pp.adoc > tmp-html.txt
mkdir -p ../HTML
(cd Resources; ./build-pp-demo.sh)
**** Error while executing command ("../../utils/stklos-pp" "Resources/fib.txt")
	 Where: in %vm-backtrace
	Reason: cannot load file "stklos/preproc"

  - %vm-backtrace
  - <<let/call>>
  - <<let/call>>
  - %cannot-load
  - require/provide
  - #[closure 7f55d5803e00]
  - #[closure 7f55d5803d40]
  - for-each
  - %do-imports
  - try-load
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
```

Why would it not find `stklos/preproc`?

(In both machines I did `rm -rf * && git reset --hard` before configuring and running `make`, so there shouldn't be leftovers from old builds -- maybe I have some missing package?)

**Comment by egallesio** [comment]
Weird. I cannot reproduce it. 
Do you have used parallel make?

**Comment by jpellegrini** [comment]
> Do you have used parallel make?

It happens with both parallel and sequential `make`...

**Comment by egallesio** [comment]
Not sure, but perhaps the last commit corrects the problem (and if it is the case, I don't understand why it worked elsewhere :wink:)

**Comment by jpellegrini** [comment]
It works now! :grin:   I really don't know what happened on the other PC, but... Well, it seems to be fixed everywhere!
