### ISSUE TITLE
A request for the README file

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#576]
@egallesio --
I have one small request for the README.md file, and it's something I can't propose as a PR...
How does one pronounce "STklos"? :grin:   It would be nice to have it on the README, no? (And perhaps on the website also)

_"STklos (pronounced ...) is a free [Scheme](http://www.schemers.org/) system ..."_

**Comment by egallesio** [comment]
Good idea @jpellegrini.
I have already modified the 2.0 README and Website to insert it.
BTW, the pronunciation is something like /ˈɛs.tɪklos/ (but I'm not good at IPA transcription).

**Comment by jpellegrini** [comment]
> BTW, the pronunciation is something like `/ˈɛs.tɪklos/` (but I'm not good at IPA transcription).

Thanks! I have chacked with [phoneme synthesis](https://itinerarium.github.io/phoneme-synthesis/) and it seems like what an american would pronouce for "S - T - klos". :)

**Comment by lassik** [comment]
So S and T are pronounced as individual letters. Is "klos" pronounced as in "close" or "closet"?

**Comment by lassik** [comment]
BTW How to pronounce [CLOS](https://en.wikipedia.org/wiki/Common_Lisp_Object_System):

http://computer-programming-forum.com/50-lisp/50435daf3a34a706.htm

> "Most of the original west-coast users say "floss"" (Gregor Kiczales

> "Kent Pitman of the X3J13 committee pronounces it "see-loss" and claims that it is the East coast way to spell (sic) it."

> Apparently, there was a tradition that if you wanted a bug fixed you pronounced it the West-coast way otherwise you could say it however you wanted.

**Comment by jpellegrini** [comment]
YAY, STklos 2.0 is out! :) :)
Great day!
:partying_face:

**Comment by egallesio** [comment]
Thanks @jpellegrini.
