### ISSUE TITLE
Respect `--mandir=`  and `--docdir` arguments to `./configure`

### ISSUE THREAD

**Issue by lockywolf** [egallesio/STklos#589]
I am building STklos like this:

```
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --disable-static \
  --build=$ARCH-slackware-linux
```

However, the man pages still go to `/usr/share/man`, not `/usr/man`, and docs go to `/usr/share/doc/`.
Could support for `mandir`  and `docdir` be added?

**Comment by egallesio** [comment]
Oops. 
Thanks, @lockywolf, for signaling this issue. 
I'll take a look at this issue very soon.

**Comment by egallesio** [comment]
This should be OK now. 
Closing this issue.

**Comment by jpellegrini** [comment]
> Closing this issue.

But... You didn't?  :grin:

**Comment by egallesio** [comment]
:disappointed:
