### ISSUE TITLE
Support `--libdir=/usr/lib64` in `./configure`

### ISSUE THREAD

**Issue by lockywolf** [egallesio/STklos#590]
Please, consider adding support for  `--libdir=/usr/lib64` in `./configure`

**Comment by lockywolf** [comment]
In my build script, I am doing `sed -i "s|/lib/|/lib$LIBDIRSUFFIX/|g" "$a/Makefile.am"`, for each `.so` file. This path should actually be coming from Autotools' $(libdir), or something like that.

**Comment by egallesio** [comment]
Hello @lockywolf,

This issue is normally fixed. Feel free to reopen it if this not the case.
Thanks for signaling this issue.
