### ISSUE TITLE
(Wishlist) Remove `MAX_TOKEN_SIZE`

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#592]
Hi @egallesio !

Not something for now, I think, since it's not a bug, but maybe `read_word` in `read.c` could work without a strict limit to the token size? Sometimes I copy a large number on the REPL and STklos can't read it.  This is also why the following fails:

```scheme
(= 
  (with-input-from-string
    (with-output-to-string 
      (lambda () (display (expt 2 30000))))
    (lambda () (read)))
  (expt 2 30000))
```

Maybe instead of calling `error_token_too_large` it could re-allocate the buffer?

**Comment by jpellegrini** [comment]
STklos has a very fast reader. Maybe, in order to keep it this way, it would be possible to:

* keep the 1024 bytes buffer, and use it
* when a token needs, it would allocate (through  libgc) more space, and keep reallocating as needed

Perhaps an `char **large_buffer` argument to the reading functions would do? When the function returns, if this is `NULL`, then the token was read as usual; if it's not NULL, it's the address of a buffer with the large token:

```c
static int read_word(SCM port, int c, char *tok, char **large_buf,   // <= here
                     int case_significant, int *last,
                     int *seen_pipe)
```

**Comment by lassik** [comment]
That's a lot of arguments. Would probably be better to use a struct?

**Comment by egallesio** [comment]
There is no more limit (except memory size, of course) on the size of a token now. 
 
```scheme
(let* ((big (expt 2 40000))
       (bigs (with-output-to-string
               (lambda () (display big)))))
  (printf "len=~s test=~s~%"
          (string-length bigs)
          (= big (read-from-string bigs))))

==> len=12042 test=#t
```

**Comment by jpellegrini** [comment]
Yay! :)   That's great!
