### ISSUE TITLE
[R7RS] `load` has an optional second argument

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#595]
Hi @egallesio !

R7RS says that `load` should accept a second optional argument:
```scheme
(load filename environment-specifier)
```
It would be a STklos module.

I looked into `lib/load.stk`, but I'm not yet familiar with that part of the code, so I didn't make a PR...

**Comment by egallesio** [comment]
It's already on my TODO list :smiley:  Don't worry, I'll do it (but probably for after 2.00, because the code about loading is too complicated and needs some rewriting).

**Comment by egallesio** [comment]
Finally, it"s here.
Last committed code resolves this issue (I forgot to mention this issue in the commit message, so I close this Issue by hand).
