### ISSUE TITLE
'ffi.h' file not found

### ISSUE THREAD

**Issue by mijodong** [egallesio/STklos#6]
I'm installing on macOS Mojave version 10.14.6, and when I try to make, I'm getting the following error:

ffi.c:31:12: fatal error: 'ffi.h' file not found
\#  include <ffi.h>

**Comment by lassik** [comment]
ffi.h is from the libffi library which can be installed from Homebrew:

```
brew install libffi
export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig
```

and then run `./configure` as you did before

**Comment by lassik** [comment]
I haven't tested the above, but that's where you can get libffi for Mac.

**Comment by mijodong** [comment]
Hi @lassik, I installed libffi from homebrew and set the PKG_CONFIG_PATH, but I'm getting the same error. I just ended up using DrRacket for what I needed.

**Comment by egallesio** [comment]
Hi @mijodong,

I apologize for the long delay to answer (I do not receive notification form github). 

This is weird. It means that, for some reason the configure script found that you have libffi installed  but the computed path to access it seem incorrect. 
If you run configure with the option --with-provided-ffi , it should work.

**Comment by salilsdesai** [comment]
@mijodong I had the same issue and it was fixed by running 
`
$ brew install pkg-config libffi
$ pip install cffi
`
(credit: https://firstblogpart2.wordpress.com/2019/04/10/ffi-h-file-not-found/)

**Comment by egallesio** [comment]
Thanks @salilsdesai for your fix. Only the first line was necessary
```
$ brew install pkg-config libffi
```
The problem comes from the fact that MacOs install libraries without installing the corresponding headers. So, `libffi` is installed whereas `ffi.h` is not.

**Comment by egallesio** [comment]
BTW, the solution I gave [previously](https://github.com/egallesio/STklos/issues/6#issuecomment-543818450) didn't work since automake the companion scripts were too old.
This is corrected now

**Comment by lassik** [comment]
Homebrew doesn't install the pkg-config `.pc` definition files into a standard place in the default pkg-config search path, so you have to add each Homebrew package manually to the search path like this:

`export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig`

`PKG_CONFIG_PATH` is a colon (`:`) separated list of directories containing `.pc` files. Subdirectories are not searched. So it's just like `PATH`.

**Comment by egallesio** [comment]
Hi @lassik ,
This is weird. I don't need to change the `PKG_CONFIG_PATH` variable to access the pc file as you said (on a Mojave machine I have access to).
pkg-config seems to retrieve everything:
```
Moyave$ pkg-config libffi --cflags
-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi
Moyave$ pkg-config libffi --libs
-lffi
Moyave$ 
```
Hope it works on other MacOs versions.
