### ISSUE TITLE
Unicode strings

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#61]
Hello,

I was going to port SRFIs  129 and130, but their tests fail. It seems that `string-length` does not work for Unicode strings:

```
stklos>
(define ABC
                (list->string (map integer->char
                                   '(#x3b1 #x3b2 #x3b3))))

stklos> (string-length ABC)
6
```

(By the way, there is a `srfi-130` branch in my copy of your repository on github)

**Comment by egallesio** [comment]
What is even weird is that 

```scheme
stklos> (string-length "\x3b1;\x3b2;\x3b3;")
3
```
I look at this one.

**Comment by egallesio** [comment]
It is corrected, but I'm afraid that this mistake could be present elsewhere... l look at that.

**Comment by egallesio** [comment]
Quickly checked on the other uses of `STk_makestring` with a second argument equal to `NULL`, and it seems OK.

**Comment by jpellegrini** [comment]
Yes, it seems to be fixed! :)
SRFI-129 tests pass, except for a problem; I'll put it in a different issue
