### ISSUE TITLE
Compilation issue: `symbol os-name unbound in module SCHEME`

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#612]
Hi @egallesio !
I see in the git logs that there are lots of nice changes  in STklos -- that's great!
However, I don't seem to be able to compile a clean checkout:

```
gcc  -g -O2 -rdynamic  -o stklos base64.o boolean.o boot.o box.o char.o cond.o cpointer.o dynload.o env.o error.o extend.o ffi.o fixnum.o fport.o gnu-getopt.o hash.o keyword.o lib.o list.o misc.o md5.o number.o object.o parameter.o path.o port.o print.o proc.o process.o promise.o read.o regexp.o signal.o sio.o socket.o sport.o stklos.o str.o struct.o symbol.o syntax.o system.o utf8.o uvector.o vector.o vm.o vport.o thread-common.o thread-pthreads.o mutex-common.o mutex-pthreads.o -lgmp  -lpcre2-8 -lpcre2-posix  -lffi  -lgc -lpthread -ldl  -lm -lpthread 
make[2]: Leaving directory '/home/jeronimo/pkg/scheme/STklos/src'
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos/src'
Making all in utils
make[1]: Entering directory '/home/jeronimo/pkg/scheme/STklos/utils'
./tmpcomp -o stklos-compile stklos-compile.stk
#[condition &error-message 140547108234752]: symbol `os-name' unbound in module `SCHEME'
**** FATAL ERROR: no handler present!
ABORT
make[1]: *** [Makefile:572: stklos-compile] Error 1
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos/utils'
make: *** [Makefile:438: all-recursive] Error 1
```

(I did `rm -rf *` then `git reset --hard`, then `./configure` and `make`)

**Comment by jpellegrini** [comment]
It also seems to happen if I try to use the binary in `src/`:
```
src/stklos 
#[condition &error-message 139657653585408]: symbol `os-name' unbound in module `SCHEME'
**** FATAL ERROR: no handler present!
ABORT
```

I had removed all files that STklos had installed before (`rm -rf /usr/local/share/stklos /usr/local/lib/stklos /usr/local/bin/stklos*`)

**Comment by egallesio** [comment]
Hi @jpellegrini,

I really don't understand. It works in my development tree and in a fresh cloned version from GitHub. But if I test in an alpine image (the same cloned version from GitHub), I have the problem you describe. That's really weird.

**Comment by jpellegrini** [comment]
I think the automated build in github also breaks, but the message is not complete there (maybe stderr/stdout are not both being shown?)

**Comment by egallesio** [comment]
It seems to be OK now. I have seen a lot of weird things, and I'll try to investigate later.  Compilation should work now :crossed_fingers:

**Comment by jpellegrini** [comment]
> Compilation should work now

It works! :)

**Comment by egallesio** [comment]
Thanks for the help.
