### ISSUE TITLE
SRFI-13: string-prefix? and string-suffix?  seems to always answer #f

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#63]
Isn't this strange?

```
stklos> (require "srfi-13")
"srfi-13"
stklos> (string-prefix? "ab" "abc")
#f
stklos> (string-prefix? "abc" "ab")
#f
stklos> (string-prefix? "a" "ab")
#f
stklos> (string-prefix? "" "ab")
#f

stklos> (string-suffix? "" "ab")
#f
stklos> (string-suffix? "b" "ab")
#f
```

**Comment by jpellegrini** [comment]
This is porbably related:

```
stklos>  (string-prefix-length ""  "")
**** Error:
string-prefix-length: bad starting index 0 on ""
	(type ",help" for more information)
```

**Comment by jpellegrini** [comment]
`%%check-indexes-func` seems to calculate `max` as `-1`, then it fails here:

```
 (unless (and (integer? start) (<= 0 start max))
	(error proc "bad starting index ~S on ~S" start str))
```

**Comment by jpellegrini** [comment]
And if I skip the index checking in `string-prefix-length`,  `%string-suffix-length` is called with `end1`=`-1`, which makes it bail out returning zero...

**Comment by jpellegrini** [comment]
See pull request #64 ... I'm working on this.

**Comment by jpellegrini** [comment]
I think PR #64  resolves this... Maybe you'll want to add more tests, or check something else?

**Comment by jpellegrini** [comment]
Checked again, the bug is gone! :)

**Comment by egallesio** [comment]
It seems OK. Thanks for the correction of this bug (and for the tests)
