### ISSUE TITLE
Should the compiler signal error on `(-)` or `(/ 1 0)`? (At compilation time?)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#647]
Not sure about this @egallesio . Tell me what you think..,.

If we turn off inlining,

```scheme
stklos> (define (f) (/ 1 0))
;; f
stklos> (define (g) (-))
;; g

stklos> (disassemble f)

000:  PREPARE-CALL        
001:  ONE-PUSH            
002:  ZERO-PUSH           
003:  GREF-TAIL-INVOKE     0 2
006:  RETURN              
007:

stklos> (disassemble g #t)

000:  PREPARE-CALL        
001:  GREF-TAIL-INVOKE     0 0
004:  RETURN              
005:
```

But with the default (inlining turned on):

stklos> (define (f) (/ 1 0))
**** Error:
/: cannot make rational with null denominator
	(type ",help" for more information)
stklos>  (define (g) (-))
**** Error:
compiler-error: -: needs at least one argument
	(type ",help" for more information)

And `disassemble-expression` signals an error:

```scheme
stklos>  (disassemble-expr '(-) #t)
**** Error:
compiler-error: -: needs at least one argument
```
The previous one was a compilre error. The following is a generic error (because it was not caught in the ilining code - easy o fix actually):
```scheme
stklos>  (disassemble-expr '(/ 1 0) #t)
**** Error:
/: cannot make rational with null denominator
	(type ",help" for more information)
```

So... Should the compiler crash when an inlinable expression is not calculable, or should we just, well, leave it there un-optimized, so it will crash when the code is executer? (I'd argue for signaling the error during compilation -- which is, leave it as it is -- as this is useful).

**Comment by egallesio** [comment]
I agree with you, everything that can be at compile time must be done at this moment  

I close this Issue, since PR #648 is merged
