### ISSUE TITLE
raise-continuable does not raise an exception?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#67]
In STklos, `raise-continuable` doesn't seem to raise an exception:

```
stklos> (raise-continuable 'a)
a
```

This is relevant for SRFI-189 (which went final today) -- since STklos does not raise an exception, two of the tests fail.

**Comment by jpellegrini** [comment]
(By the way, SRFI-189 is in my branch "srfi-189"...  I didn't make a PR yest because of those two failing tests, that have to do with this issue)

**Comment by egallesio** [comment]
It should be corrected now. The semantic I used was not exactly the same that the one found in other R7RS implementations (I'm not sure that what  had was incorrect since, I find the R7RS document *fuzzy* on this point) 

Anyway, things should be better and `raise-continuable` raise its parameter value now.

Thanks for signaling the problem.

**Comment by jpellegrini** [comment]
Yes! It works...

I have one question: if `guard` catches exceptions raised by `raise`, shouldn't it also work with `raise-continuable`?

```
stklos> (guard (x (#t (print x))) (raise "aa") 1010)
aa
stklos> (guard (x (#t (print x))) (raise-continuable "aa") 1010)
#[struct %continuable-exception 140350970552128]
1010
```

If this is the expected behavior, then the SRFI-189 tests are wrong...

**Comment by egallesio** [comment]
I have pushed a new version of `guard` This should be OK, as far as I understand what is required by this special form.

**Comment by jpellegrini** [comment]
Hm, when `guard` doesn't catch an exception and re-throws it, shouldn't it keep it "continuable" ?

```
(with-exception-handler (lambda (x) (- x))
  (lambda ()
    (guard (e ((symbol? e) (symbol>-string e)))
        (list (raise-continuable 5)))))
```

This should result in `(-5)` -- it does so in Chibi and Gauche (I mean `gauche -r7`).
But in STklos it complains as if the exception was not continuable:

```
**** Error:
error: exception handler returned on non-continuable exception
	(type ",help" for more information)
```

**Comment by jpellegrini** [comment]
* it should be `symbol->string` and not `symbol>-string` there, but it doesn't matter - that code wouldn't be executed anyway.

**Comment by egallesio** [comment]
I have pushed a new version and this should be OK this time (I hope so)

> This should result in (-5) -- it does so in Chibi and Gauche (I mean gauche -r7).

In fact with `raise-continuable` chibi and gosh evaluate to -5 . But with `raise`, result is an error on chibi (and petite), but still -5 with Gauche. Cyclone has the (old) behavior of STklos. 

It seems that everyone has a different interpretation of R7RS. Anyway, the actual implementation seems the more reasonable. 

Tell me if it is OK for you now.

**Comment by jpellegrini** [comment]
But it doesn't continue?

```
(with-exception-handler (lambda (x) (- x))
  (lambda ()
    (guard (e ((symbol? e) (symbol>-string e)))
        (list (raise-continuable 5)))))
```

Here, since the exception is continuable, after going through the handler `(lambda (x) (- x))`, the `-5` should have been sent back to the form which caused the continuable exception, and then turned into a list, resulting in `(-5)`.

At least it's what I get from R7RS... Anyway, it looks like Sagittarius and Chicken with the R7RS egg also return `(-5)` .

**Comment by jpellegrini** [comment]
I forgot to say -- it should result in the list `(-5)`, not the number `-5`, as it does now... unless I misinterpreted R7RS.

**Comment by egallesio** [comment]
Oops. This is definitively more complicate that I thought to implement and I have not yet found a writing  which is always correct :frowning_face: 

Still working on that.

**Comment by jpellegrini** [comment]
Hey, it looks good now!
