### ISSUE TITLE
Makefiles use `(cd some-dir ; do-something)`

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#689]
I was working om the Android port, and noticed that `make uninstall` removed files from the *source* tree.

This is because the Makefiles do

```
   (cd some-dir ; rm -rf ...)
```

But if `some-dir` doesn't exist... It will remove the files in the *current* directory!

Perhaps most uses of `;` in the Makefiles should be changed?

But using `&&` is not good either, since this will make the uninstall target fail if the files are not in place.

**Comment by egallesio** [comment]
Oops.

What about 

```
-(cd some-dir && rm -rf ...)
```

to ignore the error (but it will be signaled) or 

```
(cd some-dir && rm -rf ...) || true
```

???

**Comment by jpellegrini** [comment]
> `(cd some-dir && rm -rf ...) || true`

Oh, I should have thought of something like that, it's of course the right thing. I'll try to make a PR tomorrow!

**Comment by lassik** [comment]
Makefiles in the other STk and STklos repos are also using `;` instead of `&&` . For example:

* https://github.com/egallesio/STk/blob/master/Makefile.in
* https://github.com/egallesio/stklos-gtk-canvas/blob/master/stklos/Makefile.in
