### ISSUE TITLE
Encouraged behavior for include

### ISSUE THREAD

**Issue by Retropikzel** [egallesio/STklos#694]
Currently if you have this directory structure:

bar/baz.sld:
<pre>
(define-library
  (bar baz)
  (import (scheme base)
          (scheme write))
  (export hello)
  (begin
    (include "baz.scm")))
</pre>

bar/baz.scm:
<pre>
(define hello
  (lambda ()
    (display "Hello")
    (newline)))
</pre>

And you try to run it with STklos with:

stklos bar/baz.sld

you get:
<pre>
**** Error while executing command ("foo.scm")
         Where: in open-input-file
        Reason: could not open file '"baz.scm"'
</pre>

The R7RS 4.1.7 Inclusion has note:
Note: Implementations are encouraged to search for files in
the directory which contains the including file, and to provide
a way for users to specify other directories to search.

Would it be possible to search for included files in the same directory the including file is in?

In the situation where the library amount grows, say to even 5 libraries telling the implementation (for example with a flag) where to include files from is not as ideal. But it would be better than nothing. Or maybe even both could be added?

**Comment by egallesio** [comment]
Hi @Retropikzel, 

You are right. I will change that soon. 
Thanks for signaling the problem.

**Comment by egallesio** [comment]
I think it is correct now. 

> In the situation where the library amount grows, say to even 5 libraries telling the implementation (for example with a flag) where to include files from is not as ideal. But it would be better than nothing. Or maybe even both could be added?

I'm not sure to understand what you said here, and hence if I answer to your question. Anyway, there are:

 - the `load-path` parameter object which permit to determine the paths where files are searched
 -  the `-I` and `-A` options of the `stklos` and `stklos-compile` commands, which can be used to prepend and append a path to the previous parameter object.

In this commit, the containing directory of the `.sld` file is automatically prepended to `load-path` just before including the file. So, you don't have to play with `load-path` in the example you gave.

**Comment by lassik** [comment]
AFAIK the load path should apply to `import`, not `include`.

`include` should always be relative to the source file in which it occurs.

**Comment by Retropikzel** [comment]
> I think it is correct now.
> 
> > In the situation where the library amount grows, say to even 5 libraries telling the implementation (for example with a flag) where to include files from is not as ideal. But it would be better than nothing. Or maybe even both could be added?
> 
> I'm not sure to understand what you said here, and hence if I answer to your question. Anyway, there are:
> 
>     * the `load-path` parameter object which permit to determine the paths where files are searched
> 
>     * the `-I` and `-A` options of the `stklos` and `stklos-compile` commands, which can be used to prepend and append a path to the previous parameter object.
> 
> 
> In this commit, the containing directory of the `.sld` file is automatically prepended to `load-path` just before including the file. So, you don't have to play with `load-path` in the example you gave.

What I meant with situations where there are for example 5 libraries, each with inluded file in different directory, and implementation not having the directory of file containing the (include...) automatically. One would have to have 5 different -I ../somepath as arguments. And so the automatic inclusion of those paths is much preferred.

Thank you for the fix. I appreciate it.

 Are load path and include path in STklos the same?

**Comment by egallesio** [comment]
> AFAIK the load path should apply to `import`, not `include`.

I think the notion of load path do not exist for R7RS. Am I wrong?  

> `include` should always be relative to the source file in which it occurs.

Yes, I'm not comfortable with `include` which use `load-path` (I didn't ever use it, because I thought it was not the case, but see that it was not the case when working on this issue :laughing:) .

Note that the load-path,is only changed for the inclusion and restored just after. So it is not so different. 
Changing `include` to be relative to the includer file is easy. For now, the include file is searched in a path that is 
`(cons dir (load-path))`, where `dir` in the containing directory of the includer. I can change it to `(list dir)`.

Using the `load-path` is useful when building an object file in the parent directory of the library. For instance, we can do

```
$ stklos-compile  -I bar -o bar.ostk bar/baz.sld` 
```

Otherwise, we have to do something like
  
```
$ (cd bar; stklos-compile -o ../bar.ostk baz.sld)
```

Not a big deal, in fact.

**Comment by egallesio** [comment]
> What I meant with situations where there are for example 5 libraries, each with included file in different directory, and implementation not having the directory of file containing the (include...) automatically. One would have to have 5 different -I ../somepath as arguments. And so I think the automatic inclusion of those paths is preferred.

:+1: 

> Thank you for the fix. I appreciate it.

Yo're welcome

> Are load path and include path in STklos the same?

As I said in my reply to @lassik, yes. The change I gave in it could be applied to not use  `load-path`.
I have to make some tests to see, if I change that.

**Comment by lassik** [comment]
> I think the notion of load path do not exist for R7RS. Am I wrong?

I think you're right. RnRS says almost nothing about the file system.

> For now, the include file is searched in a path that is
> `(cons dir (load-path))`, where `dir` in the containing directory of the includer. I can change it to `(list dir)`.

`(list dir)` sounds correct to me.

**Comment by egallesio** [comment]
> `(list dir)` sounds correct to me.

This is the default behavior now. However, I have added a new parameter object `includes-use-load-path' to eventually permit the use of  `load-path`. By default, this parameter is set to false.  Furthermore, I have fixed the compilation problem exposed before. You can compile

```sh
$ stklos-compile  -o bar.ostk bar/baz.sld` 
```

without juggling with options that modify `load-path`.

**Comment by Retropikzel** [comment]
Thank you!
