### ISSUE TITLE
Can't cross-compile

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#7]
Hello.
I am trying to cross-compile STKlos so it runs on a MIPS machine, running Linux (it's a wireless router, runs OpenWRT).

Compilation is done inside the OpenWRT buildroot, which does a lot of things automatically. i have set the configure step as this:

```
CONFIGURE_ARGS += --host=mipsel-openwrt-linux-musl --build=x86_64-unknown-linux-gnu --with-provided-bignum --with-provided-ffi --with-provided-regexp --with-provided-gc

define Build/Configure
        (cd $(PKG_BUILD_DIR) && ./configure $(CONFIGURE_ARGS))
endef
```

However, the configure arguments are ignored when the GC `configure` script runs.

```
*****
***** GC support
*****
checking for GC_malloc in -lgc... no
... Configuring libgc
configure: loading site script /home/jeronimo/pkg/openwrt-18.06.2/include/site/mipsel
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking GC version numbers... major=8 minor=0                 micro=4
checking for a BSD-compatible install... /usr/bin/install -c
```

The host and target systems should not be `x86_64-unknown-linux-gnu`, but `mipsel-openwrt-linux-musl` instead. The STKlos configure script itself got the right parameters.

I have tried forcing the script to run `configure` on the gc subdir first,

```
define Build/Configure
	(cd $(PKG_BUILD_DIR)/gc && ./configure $(CONFIGURE_ARGS) --with-libatomic-ops=none)
	(cd $(PKG_BUILD_DIR) && ./configure $(CONFIGURE_ARGS) --with-libatomic-ops=none)
endef
```
but then it will enter the gc directory, run `configure` properly, get out of it, and then run the STKlos `configure`, which will call the gc `configure` again -- this time without the correct options.

Maybe the configure script is not passing options to the other scripts (in gc, ffi, pcre, gmp directories)?

**Comment by jpellegrini** [comment]
This is the output of compilation with

```
(cd gc && ./configure)
(./configure)
```

[stklos-compile-no-autoreconf.txt](https://github.com/egallesio/STklos/files/4139406/stklos-compile-no-autoreconf.txt)

**Comment by egallesio** [comment]
Hi @jpellegrini ,

That is a great news that you are trying to port STklos on OpenWRT/MIPS. 
The problem is that  we cannot pass all the parameters to the main configure script to the one in subdirectories since they will most of them will be rejected by the configure scripts. The only parameters from the main scripts which are passed to the libraries are CC and CFLAGS. Should the 
--host and --build be passed to them too?

**Comment by jpellegrini** [comment]
Yes, --host and --build are important, but I'm not sure what other parameters should be passed (the buildroot used in OpenWRT is a complex environment).

I'll try passing --build and --host and see if it works.

Anyway, using system libraries and none provided works perfectly for cross-compiling.

**Comment by jpellegrini** [comment]
I have made libgc packages for OpenWRT, so it is possible to get STklos running.

I'm not sure if this bug is still relevant -- it would be nice if STklos could be compiled with its own libgc on different platforms, but for OpenWRT this is already dealt with in a different way.

**Comment by egallesio** [comment]
I don't understand: Do you have installed a new libgc globally or have you tried to configure with the --with-provided-gc option?

**Comment by jpellegrini** [comment]
I have packaged and installed libgc on OpenWRT, so using `--with-provided-gc` is not necessary.

**Comment by egallesio** [comment]
Do you think that we can close this issue? 
If you think so, can you close it?

**Comment by jpellegrini** [comment]
Yes, sure!
