### ISSUE TITLE
ANSI color codes - repeated escape sequences

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#72]
Hi,

It looks like the `ansi-color` procedure produces repeated color escape codes, and this confuses at least one terminal emulator (terminology, the one which comes with Enlightenment).

```
(string->list (string-append (ansi-color  'normal "aaa" 'clear) (do-color (get-repl-color :prompt) "bbb" 'clear  (get-repl-color :input) " -")
))
(#\escape #\[ #\0 #\m #\a #\a #\a #\escape #\[ #\m #\escape #\[ #\1 #\; #\3 #\5 #\m #\b #\b #\b #\escape #\[ #\escape #\[ #\0 #\; #\1 #\m #\space #\-)
```

The opening of the color code right after "bbb" is repeated, `\e[\e[`.

A bach script with this single line,

```
echo -e "\e[m\e[1;35mHello\e[\e[0;1m!!!\e[0m"
```
for example, produces 

```
Hello0;1m!!!
```

because the escape opening before "!!!" is repeated.

So, Terminology  prints the prompt with the correct color, but also prints `0;1m` between the prompt and the input. This also complicates readline, since the number of characters from cursor to the beginning of editable area is wrongly computed:

```
stklos>0;1m
```

As far as I could see, this happens when two adjacent color codes are passed to `do-color`.
For the prompt, I removed the `'clear` between prompt and input, and it worked  fine:

```
(define (make-prompt module)
  (let ((str1 (if (> repl-level 1) (format "[~A] " repl-level) ""))
        (str2 (format "~A>" (module-name module))))
    (repl-prompt (if (repl-prompt-use-color?)
                     (string-append
                        (do-color (get-repl-color :repl-level) str1 'clear)
                        (do-color (get-repl-color :prompt) str2 ;'clear   <== here, commented out
                                  (get-repl-color :input))
                        " ")
                     (string-append str1 str2 " ")))))
```

For the initial banner, I see that either adding an empty string,
```
      (display (do-color 'normal "" col1 "  \\    " col2 line1 'clear))
```
or not using the initial `normal`,
```
      (display (do-color 'normal "" col1 "  \\    " col2 line1 'clear))
```

also works. But these are workarounds...

I don;t know what the ANSI escape code spec says about those (and wether the fault is Stklos' or Terminology's), but it would be nice anyway to not output repeated or non-closed codes.

**Comment by lassik** [comment]
ANSI codes are of the form:

* `#\escape #\[ <digits>#\m`
* `#\escape #\[ <digits> #\; <digits> #\m`
* etc.

So our ANSI emitter has a bug. Here's a short way to reproduce it:

```
(do-color 'normal 'bold 'normal 'bold)   => "\x1b;[0;1;0;1m"       ; correct
(do-color '(normal bold) '(normal bold)) => "\x1b;[0;1\x1b;[0;1m"  ; incorrect
```

The bug is [here](https://github.com/egallesio/STklos/blob/afab62a760755958c6c4ca4cc2054d0bea339abe/lib/bonus.stk#L920). When flattening a sublist, it forgets whether or not it was building an ANSI escape before it got to the list.

**Comment by jpellegrini** [comment]
@lassik I tried running STklos with your patch, and the result is still the same...

```
(string->list (string-append (ansi-color  'normal "aaa" 'clear) (do-color (get-repl-color :prompt) "bbb" 'clear  (get-repl-color :input) " -")))
```

still shows the repeated sequence... And terminology still shows the `0;1m` after the prompt.

**Comment by lassik** [comment]
The current output works like this:

```scheme
> (ansi-color 'clear 'bold)
"\x1b;[;1m"
```

So `'clear` is encoded as a blank [SGR parameter](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR), not as a number.

Clear can also be encoded as the parameter number `0`. I can't find where `clear` is defined in the STklos source, but try changing it to `0` instead of blank and see if that solves the problem.

**Comment by jpellegrini** [comment]
ooh, wait! @egallesio should it really be `clear`? Or should the code used in `repl.stk` have been `normal`?

```
      (display (do-color 'normal col1 "  \\    " col2 line1 'clear))
      (display (do-color 'normal col1 "   \\   " col2 line2 'clear))
      (display (do-color 'normal col1 "  / \\  " col2 line3 'clear))
      (display (do-color 'normal col1 " /   \\ " col2 line4 'clear))))
```

The ANSI color code table in `bonus.stk` only defines `'normal`... So `'clear` probably falls through some `case` or something like that.

**Comment by jpellegrini** [comment]
* it looks like the current code actually works, and what was missing is to touch boot.stk. It's really strange, because I had done a distclean followed by a fresh build, and still boot.stk wasn't compiled (?)

Anyway, it seems like this bug is fixed...

About `clear`:  I guess it is intended to generate a blank SGR parameter, indeed, and it seems to be working.

**Comment by lassik** [comment]
> So `'clear` probably fails to be found in the assoc list, and returns the default, which is the empty string!

You're right. The code that looks them up in the assoc list is [here](https://github.com/egallesio/STklos/blob/afab62a760755958c6c4ca4cc2054d0bea339abe/lib/bonus.stk#L871).

> (Is this a good default, btw?)

The blank string is the same as SGR `0`, i.e. reset all display attributes to defaults. You can test it from sh/bash with `printf 'default \x1b[31m red \x1b[m default\n'`

So any unknown color code would reset the foreground and background color, bold, etc. It's not a bad default. We could also raise an exception, but is that too strict?

**Comment by lassik** [comment]
In any case, to avoid confusion, it would be best to rename all `clear` to `normal`. `normal` is explicitly defined as `0` in the lookup procedure above.

**Comment by egallesio** [comment]
Yes it is best to rename the `clear` in `boot.stk` with `normal`. Anyway, I think that the default that returns an empty string should remain. I do modify the repl file.

**Comment by egallesio** [comment]
If I have understood it is already OK for you @jpellegrini. The version I just pushed should not change things. I let you close this issue  if it is effectively OK for you :crossed_fingers:

**Comment by jpellegrini** [comment]
Yes, it works now! The escape sequence is correct, and the prompt looks fine again.
