### ISSUE TITLE
Question on optimizing code in SRFI reference implementations

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#74]
Is it a goal?

For example, SRFI-133 (see pull request #73) recommends some optimization, but there are some Scheme implementations that do not do that (Chicken, for example - which is not a slow Scheme).

I was checking SRFI-132, Sort Libraries, and there is the same recommendation,

> _You could speed up the vector code a lot by error-checking the procedure parameters and then shifting over to fixnum-specific arithmetic and dangerous vector-indexing and vector-setting primitives. The comments in the code indicate where the initial error checks would have to be added. There are several (quotient n 2) calls that could be changed to a fixnum right-shift, as well, in both the list and vector code. The code is designed to enable this — each file usually exports one or two "safe" procedures that end up calling an internal "dangerous" primitive. The little exported cover procedures are where you move the error checks.
> 
> This should provide big speedups. In fact, all the code bumming in the source pretty much disappears in the noise unless you have a good compiler and also can dump the vector-index checks and generic arithmetic — so it's really set up for optimization rather than fully optimized._

So, do I optimize when submitting?  I'd then write some new procedures in C.

**Comment by lassik** [comment]
The sample implementations are meant to be correct - not necessarily fast. Thus, it's a good idea to optimize speed-critical parts for each Scheme implementation. However, an unoptimized implementation can still be useful.

Chicken compiles Scheme to C, a strategy that produces quite fast code even without manual optimization. I suppose they ran some benchmarks and decided that the unoptimized version is fast enough.

**Comment by jpellegrini** [comment]
SRFI-133 has been implemented with the performance-critical parts in C, SRFI-27 was re-written for speed, and we've been implementing mixed SRFIs successfully, so I guess the raison d'etre of this issue is void... Can we close this?

**Comment by egallesio** [comment]
You are right. I close it.
