### ISSUE TITLE
Git information in -V output

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#75]
Would there be simple way to add the Git properties from SRFI 176 into the `-V` output?

```
(build.git.tag string)
(build.git.branch string)
(build.git.commit string)
(build.git.modified string…​)
```

Tag: `git describe --tags --abbrev=0 2>/dev/null || true`
Branch: `git rev-parse --abbrev-ref HEAD 2>/dev/null || true`
Commit: `git rev-parse --short HEAD 2>/dev/null || true`
List of files with uncommitted changes:
```
printf '(build.git.modified';
git diff-index --name-only HEAD 2>/dev/null | head | xargs -n 1 printf ' "%s"';
echo ')'
```

Git information cannot be retrieved by the `./configure` script, since all kinds of Git operations can be done between `./configure` and `make`. The information would have to be computed by `make` somehow.

**Comment by jpellegrini** [comment]
The `Makefile` could output to a `git_config.h` file, and this one would then be included in stklos. Should work...

**Comment by lassik** [comment]
The [SRFI's sample implementation](https://github.com/scheme-requests-for-implementation/srfi-176/tree/master/implementation) contains an example of that approach in the file `scheme-build.sh`. That shell script generates a `scheme_env_build.c` like you suggest.

**Comment by jpellegrini** [comment]
> The `Makefile` could output to a `git_config.h`

Even better - there is already a `stklosconf.h`...

**Comment by lassik** [comment]
The top of `stklosconf.h` says:

```C
/* src/stklosconf.h.  Generated from stklosconf.h.in by configure.  */
/* src/stklosconf.h.in.  Generated from configure.ac by autoheader.  */
```

So if we append our own stuff in there, `./configure` will probably overwrite it.

**Comment by jpellegrini** [comment]
> The top of stklosconf.h says:

Yes. I thought it would be possible for the Makefile to append information to `src/stklosconf.h`, but I realize this would be fragile.

**Comment by lassik** [comment]
I agree (purely based on intuition, not proof). It's probably more reliable to use a different file.

**Comment by jpellegrini** [comment]
However, I always have problems with autotools. I don't know where to include the code, since `Makefile.am` doesn't seem to have a rule that would do something like "compiling"...

**Comment by lassik** [comment]
I also am not acquainted with automake.

It's a bit complex since the git information can basically change whenever anything else changes, since we're tracking everything in git. That's a lot of changes. So in the Makefile, our `git_config.h` file would have a dependency on every other file (!). Something like that :) This problem is more complex than I thought when `make` is involved.

**Comment by jpellegrini** [comment]
One could _assume_ that, once `make` was called on the command line, no changes were done which are relevant to git information (which I think is reasonable)...

But I agree, this needs to be in  `Makefile`, not the configure script.

**Comment by lassik** [comment]
It's reasonable to assume that between starting `make` and getting the finished executable, no Git changes are done. But editing files and making commits before running `make` changes the Git info. The right place to get the git info would be every time when running `make`.

**Comment by lassik** [comment]
I tried the following shell script `git_config.sh`:

```sh
#!/bin/sh
set -u
git_tag="$(git describe --tags --abbrev=0 2>/dev/null)"
git_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
git_commit="$(git rev-parse --short HEAD 2>/dev/null)"
cat >git_config.c <<EOF
// Generated by git_config.sh each time 'make' is run.
const char env_build_git_tag[] = "$git_tag";
const char env_build_git_branch[] = "$git_branch";
const char env_build_git_commit[] = "$git_commit";
EOF
```

It writes a C file like this:

```C
// Generated by git_config.sh each time 'make' is run.
const char env_build_git_tag[] = "stklos-1.40";
const char env_build_git_branch[] = "master";
const char env_build_git_commit[] = "840e52b";
```

According to `time ./git_config.sh ` it takes 0.03-0.04 seconds on my computer. So it shouldn't be so slow as to cause problems. The main issue is whether it's simple enough to add to the `Makefile` without resorting to some dirty hack :)

**Comment by jpellegrini** [comment]
It seems one can use this in `Makefile.am`:

```
GIT_TAG := "$(shell git describe --tags --abbrev=0 2>/dev/null)"
```

and add this to `CFLAGS`:

```
-D_GIT_TAG=\"$(GIT_TAG)\"
```

and use `_GIT_TAG` in the C code.

https://stackoverflow.com/a/12368262

**Comment by jpellegrini** [comment]
> The main issue is whether it's simple enough to add to the `Makefile` without resorting to some dirty hack :)

Maybe the file generated by your solution could be a header file (not a C file), included by `stklos.c`?

Or -- there is also the env var solution I pointed out... But I'm nut sure which one is preferable.

**Comment by lassik** [comment]
Sure, both of those are fine. The envar solution didn't occur to me. It would be simpler, unless there is a lot of text (which makes the compiler command lines very long).

**Comment by jpellegrini** [comment]
One thing: the code that retrieves the git information would need to check if it is inside a git checkout (it could be a tarball without the `.git` subdirectory). 

I suppose it's not needed to verify wether the git info is really related to the STklos git repo? I could, in theory, have a STklos release (without the git subdir) as a subdirectory of a git project, and then the `git describe` command would rertieve info from this other project...

**Comment by lassik** [comment]
> One thing: the code that retrieves the git information would need to check if it is inside a git checkout (it could be a tarball without the `.git` subdirectory).

Good point.

The `git` command writes an error message to stderr and exits with a nonzero status when it is run outside a Git repo. Hence a command like `git rev-parse --short HEAD 2>/dev/null || true` will succeed with blank output outside a repo. The `2>/dev/null` silences the stderr output, and `|| true` makes sure the exit code is always zero (success).

> I suppose it's not needed to verify wether the git info is really related to the STklos git repo? I could, in theory, have a STklos release (without the git subdir) as a subdirectory of a git project, and then the `git describe` command would rertieve info from this other project...

Even better point. I can't think of any way to solve this problem in general, without embedding some kind of manifest file (with checksums of every file known to be part of STklos) and checking the manifest against `git ls-files`. It gets really difficult and slow. And much of the point of Git is that you can make changes to the files, which would change the checksums. The problem just seems too hard, and unlikely to occur in practice.

**Comment by jpellegrini** [comment]
What about this?

* The sript that retrieves git information stays in `src/`,which is where the C files are (and the `.h` file would be generated there);
* The script checks for a `../.git` directory. If it exists, retrieve the information. If not, don't include it.

**Comment by lassik** [comment]
> * The sript that retrieves git information stays in `src/`,which is where the C files are (and the `.h` file would be generated there);

Sounds good.

> * The script checks for a `../.git` directory. If it exists, retrieve the information. If not, don't include it.

I would just always run the `git` commands instead of checking for the directory. Git has a a feature where you can put the `.git` directory to a non-standard place, so it's not trivial to find it. `time git rev-parse --short HEAD` shows that the command takes 0.006 seconds when run outside a Git repo, so it doesn't really cost anything.

**Comment by jpellegrini** [comment]
> Git has a a feature where you can put the .git directory to a non-standard place, so it's not trivial to find it

Ok, so there is really no way to tell.

One possible workaround (not perfect) would be to include `git remote -v` information in the generated header file.
Then `(version-alist)` could report

```
(git.repositories ("origin"	     "https://github.com/jpellegrini/STklos.git")
                  ("upstream"	     "https://gitlab.com/Gallesio/STklos.git")
                  ("upstream-github" "https://github.com/egallesio/STklos.git"))
```

This is an actual example of how it would work with my setup. :)

**Comment by lassik** [comment]
> > Git has a a feature where you can put the .git directory to a non-standard place, so it's not trivial to find it
> 
> Ok, so there is really no way to tell.

The only sure way to tell is to run some `git` subcommand that tells you the gitdir. But if we're running `git` anyway, we might as well directly run the `git` command to print the information we want. It should take less than 0.05 seconds to run all the git commands we need so nobody would notice a slowdown.

> One possible workaround (not perfect) would be to include `git remote -v` information in the generated header file.
> Then `(version-alist)` could report
> 
> ```
> (git.repositories ("origin"	     "https://github.com/jpellegrini/STklos.git")
>                   ("upstream"	     "https://gitlab.com/Gallesio/STklos.git")
>                   ("upstream-github" "https://github.com/egallesio/STklos.git"))
> ```
> 
> This is an actual example of how it would work with my setup. :)

That could certainly be done, but it doesn't tell you which remote you are using for the current code. Git is fundamentally asynchronous, so that "push" and "pull" are always manual operations. It never synchronizes anything automatically. So even if you have particular remotes, there is no guarantee that any local branch corresponds to a particular remote branch. That's why we use commit hashes a lot - they have cryptographic protection to guarantee that you really are using the same version of the code. (We usually shorten them to the 6 or 7 first hex digits, so the protection is not as strong (fun hack: [gitbrute](https://github.com/bradfitz/gitbrute)), but it still easily prevents accidental errors.

**Comment by lassik** [comment]
Perhaps what you're looking for is something like this:

```
$ git branch -vv
  example f7fc7b0 [jpellegrini/android] Add INSTALL-android
* master  e14c57d [upstream/master] The STklos boot image is always rebuilt now after a make distclean
```

The output tells you that:

* the local `example` branch is tracking the `android` branch at the remote named `jpellegrini`
* the local `master` branch is tracking the `master` btanch at the remote named `upstream`
* the active (currently checked out) local branch is `master`

Note that the remote names are arbitrary -- I'm using the name `upstream` for Erick's STklos repo, but anyone who clones the repo could use any other name.

**Comment by lassik** [comment]
The phrase "local branch `foo` is tracking remote branch `bar/baz`" means that "git push" and "git pull" use that remote branch by default. It doesn't guarantee that code is actually synchronized with that branch. Git is very lenient about these things - you can push and pull with other remotes and other local/remote branches as well, in any combination. Those are just the default settings for convenience.

**Comment by jpellegrini** [comment]
> Perhaps what you're looking for is something like this:

Yes, of course. I'm sorry, I agree it makes no sense to include all the branches the user has. But what you mentioned could be interesting (the current checked out branch) -- do you agree?

**Comment by lassik** [comment]
> Yes, of course. I'm sorry, I agree it makes no sense to include all the branches the user has.

No problem :)

> But what you mentioned could be interesting (the current checked out branch) -- do you agree?

SRFI 176 has the following [standard properties for Git](https://srfi.schemers.org/srfi-176/srfi-176.html#_build_properties):

```
(build.git.tag string)
(build.git.branch string)
(build.git.commit string)
(build.git.modified string…​)
```

`build.git.branch` is the currently checked out branch, as you suggest. I agree that it's useful (but only in combination with the commit hash, since new commits are added to branches all the time).

I personally like the `build.git.modified` (which lists the names of all files tracked in Git that have been modified since the commit) but projects don't commonly use it. It can be confusing if you believe you compiled from a particular commit, but in fact your working tree had some changes to it.

SRFI 176 also lists `git` commands that can be used to find out all that info.

**Comment by jpellegrini** [comment]
Oh, look what I just found:
https://stackoverflow.com/questions/43526939/how-to-insert-git-based-version-in-autoconf-managed-project

**Comment by jpellegrini** [comment]
@lassik see PR #99 !

**Comment by egallesio** [comment]
Can we close this Issue?

**Comment by lassik** [comment]
> Can we close this Issue?

Yes. Just built the latest `master` and it works great! Thank you for investigating this issue so thoroughly.
