### ISSUE TITLE
disassemble is not documented

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#81]
I got used to disassembling code a lot when I programmed in Common Lisp (with SBCL).
I just found that STklos has a `disassemble` procedure! But it isn't mentioned in the manual...

**Comment by egallesio** [comment]
That's true. I have not documented it because I thought that it implies to also document the VM instructions. But perhaps it is a weird idea and `disassemble` could be documented  without describing those instructions. What do you think?

**Comment by jpellegrini** [comment]
I think it would be OK to have disasemble documented... The VM opcodes are not completely esoteric after all  :)

I will see if I come up with an initial documentation of the opcodes. Maybe at least part of them.

**Comment by egallesio** [comment]
> I think it would be OK to have disasemble documented... The VM opcodes are not completely esoteric after all :)

That's true. Do, I have added some minimal documentation for it. It is pushed.

> I will see if I come up with an initial documentation of the opcodes. Maybe at least part of them.

That's a lot of work and it is probably the most urgent thing to do. Furthermore,  the interested public would be  relatively small imho.

**Comment by jpellegrini** [comment]
>  the interested public would be relatively small imho

I agree, but if 2 more people understand the VM and can contribute, it would be nice, wouldn't it? :)

I have a partial document for some opcodes (immediate values, arithmetic, basic stack operations).  It's markdown, but I can change to something else if needed.

**Comment by jpellegrini** [comment]
Ok, I made a PR (#85 )...

**Comment by egallesio** [comment]
> I agree, but if 2 more people understand the VM and can contribute, it would be nice, wouldn't it? :)

Yep! you're right.

A great contribution! Thanks.

**Comment by jpellegrini** [comment]
@egallesio do you think `vm.adoc` is already good enough that we could close this issue?
