### ISSUE TITLE
SRFI-175 not listed in *all-features*

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#83]
I don't understand.

```
stklos> (features)
(stklos STklos STklos-1.40 id-5b7feb4 almost-r7rs exact-complex ieee-float full-unicode utf-8 UTF-8 ratios unix little-endian srfi-0 srfi-1 lists srfi-2 and-let* srfi-4 hvectors srfi-6 srfi-7 program srfi-8 srfi-9 records srfi-10 srfi-11 srfi-13 strings srfi-14 charsets srfi-16 case-lambda srfi-17 srfi-18 srfi-22 srfi-23 error srfi-26 srfi-27 random srfi-28 srfi-30 srfi-31 srfi-34 srfi-35 srfi-36 conditions srfi-37 args-fold srfi-38 srfi-39 parameters srfi-45 srfi-48 srfi-51 rest-list srfi-54 formatting srfi-55 srfi-59 srfi-60 srfi-62 srfi-66 srfi-69 hash-tables srfi-70 srfi-74 srfi-87 srfi-88 srfi-89 srfi-96 srfi-98 srfi-100 srfi-111 boxes srfi-112 srfi-117 queues-as-lists srfi-129 titlecase srfi-141 integer-division srfi-145 srfi-151 bitwise-ops srfi-156 srfi-158 srfi-161 srfi-169 srfi-171 transducers srfi-173 hooks srfi-174 posix-timespecs srfi-176 srfi-180 JSON json srfi-190 generators)
```

But it *is* there:

```
stklos> (require "srfi-175")
"srfi-175"
stklos> ascii-string-ci<=?
#[primitive ascii-string-ci<=?]
```

And it *is* listed in `*all-features*`, in `srfi-0.stk`:

```
 ...
    ((srfi-173 hooks) "srfi-173")       ; Hooks
    ((srfi-174 posix-timespecs) "srfi-174")
                                        ; POSIX Timespecs
    ((srfi-175 ascii) "srfi-175")       ; ASCII character library
    srfi-176                            ; Version flag
    ;; srfi-177                         ; Portable keyword arguments (draft)
 ...
```

What could be happening?

I did `make uninstall`, `make distclean`, `autoreconf`, and installed again, just to be sure, but it doesn't seem to be listed...

**Comment by lassik** [comment]
Does `touch lib/boot.stk; make` help?

**Comment by jpellegrini** [comment]
Yes.
But it is totally weird that a distclean followed by a new install doesn't fix it!

And -- by the way, after I did `touch lib/boot.stk; make`, the color codes in the REPL (bug #72 ) were good again!

**Comment by lassik** [comment]
Good to hear!

The `touch` updates the last-modified timestamp, forcing the Scheme image to be rebuilt. Perhaps a `clean` or `distclean` should force a rebuild as well, but bootstrapping tends to be tricky. We'd best ask @egallesio what to do.

**Comment by egallesio** [comment]
> But it is totally weird that a distclean followed by a new install doesn't fix it!

You are right. I modified the `lib/Makefile.am` so that a `make distclean` will always rebuid the image.

> but bootstrapping tends to be tricky.

I agree!!  :roll_eyes:

**Comment by jpellegrini** [comment]
Well, SRFI-175 is there now :)
So I think we can close this...
