### ISSUE TITLE
make sometimes does not rebuild the Scheme image

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#84]
Continuing from #83:

Sometimes `make` builds a version of STklos using the old Scheme image even when changes have been made to the Scheme source code in `lib`. A manual workaround is `touch lib/boot.stk; make` but it would be great to find a way to automate this.

**Comment by jpellegrini** [comment]
One way would be declaring the boot target as `.PHONY` in `Makefile.am` -- I *suppose* (I always have a problem with autotools)...
That would force it to always run - but it would remake the boot image even when not needed.

**Comment by jpellegrini** [comment]
(I mean, the `Makefile.am` in `lib/`)

**Comment by egallesio** [comment]
Normally the files that must provoke an image rebuilding are in the scheme_BOOT list of `lib/Makefile.am`. This list contains the files that are directly (or indirectly) included in `boot.stk`. It is very possible that some dependence is not listed in this variable. Do you think to a particular file?

**Comment by lassik** [comment]
The following `.stk` files have been modified in the last 100 commits:

`git log --stat -n 100 | grep '^ .*.stk ' | sed 's@^ @@' | sed 's@ .*@@' | sort | uniq`

```
doc/skb/lib.stk
doc/skb/srfi.stk
lib/bonus.stk
lib/boot.stk
lib/compiler.stk
lib/r7rs.stk
lib/repl.stk
lib/srfi-0.stk
lib/srfi-100.stk
lib/srfi-117.stk
lib/srfi-129.stk
lib/srfi-13.stk
lib/srfi-141.stk
lib/srfi-151.stk
lib/srfi-156.stk
lib/srfi-161.stk
lib/srfi-171.stk
lib/srfi-174.stk
lib/srfi-180.stk
lib/srfi-37.stk
lib/srfi-69.stk
tests/do-test.stk
tests/test-json.stk
tests/test-misc.stk
tests/test-srfi.stk
tests/test-utf8.stk
tests/test.stk
```

So there are no obvious files missing from `scheme_BOOT`.

**Comment by lassik** [comment]
Commit `e14c57d`: The STklos boot image is always rebuilt now after a make distclean

**Comment by lassik** [comment]
Commit e14c57d: The STklos boot image is always rebuilt now after a make distclean

**Comment by jpellegrini** [comment]
I believe this is fixed, no?

**Comment by egallesio** [comment]
Yep, for me it is fixed.
