### ISSUE TITLE
STklos does support parallel compilation! (But this is not documented)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#87]
I;m not sure where to document this, but STklos does support parallel compilation. I have been running `make -j10` everytime I build STklos, and it never failed because of that.

I see that STklos uses the standard GNU autotools INSALL file; I'm not sure if it would be better to change it or to write different instructions.

**Comment by egallesio** [comment]
> I;m not sure where to document this, but STklos does support parallel compilation. I have been running `make -j10` everytime I build STklos, and it never failed because of that.
> 

Yes, parallel compilation is supported now (it was not always the case). For me it is "normal" and I don't know if it has to be explicitely documented. Perhaps here: https://www.stklos.net/documentation.html#installing-from-sources.
Anyway, I'm not sure that this is really "visible'.

> I see that STklos uses the standard GNU autotools INSALL file; I'm not sure if it would be better to change it or to write different instructions.

It is very general but it contains a lot of things (uninstall, compilation for multiple architectures, ...). I'm not sure that it should be changed. Or perhaps, we could have a prelude which is basically what we have in the link before (a sort of *TL;DR*)  followed by the current INSTALL content. 

What do you think?

**Comment by jpellegrini** [comment]
> Perhaps here: https://www.stklos.net/documentation.html#installing-from-sources.

That would help, yes.
It's not the most important thing in the world anyway... :)

**Comment by jpellegrini** [comment]
Made a PR... #95

**Comment by egallesio** [comment]
The new file `QUICK-INSTALL.md` contains now this information. 
The web site has been updated accordingly.

**Comment by jpellegrini** [comment]
That's great!
