### ISSUE TITLE
Makefile in lib/ uses ld instead of expanding the loader macro

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#88]
After a while I tried again to compile STklos on OpenWRT, and it seems that the C part of SRFI-175 won't compile. This is because the compiler (CC) part of the Mkaefile is correct, but the linker (LD) is not:

```
.c.so :
         mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/home/jeronimo/pkg/openwrt-19.07/build_di    r/target-mips_24kc_musl/STklos-4ab30686b5c6b634abb36eef3c53e90abfda2073=STklos-4ab30686b5c6b634abb36eef3c53e90abfda2073 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -fpic -nostdlib -I../src -I../gc/include -c  -o $*.o $*.c
         ld -shared -o  $*.so $*.o
         /bin/rm -f $*.o
```

If correctly expanded `$CC` fo `mips-openwrt-...`, but kept `ld` from the host machine. Of course, `ld` will complain that I am trying to mix two architectures!

This really should be no problem, since the linker is already used in the `src` directory for the core of STklos... Not sure why `ld` was used instead of `$LD` in `lib/`.

The `.c.@SH_SUFFIX@` suffix in `Makefile.am` seems to be correct, but I am no autotools expert...

**Comment by egallesio** [comment]
If the LD variable is defined as a shell variable when you launch `configure`, it should be OK.

**Comment by jpellegrini** [comment]
Aha! It works! 
Thank you!

**Comment by egallesio** [comment]
Yes but it does not work anymore with Github CI :frowning_face: !!!

**Comment by jpellegrini** [comment]
That is strange. Can you check wether `LD` is set, and if it's not, use `ld`?
(I am really not good with autotools)

**Comment by egallesio** [comment]
This is what I have done. This is OK now with github, still waiting with Docker hub.
Why it worked on my machine is another mystery.

> (I am really not good with autotools)
Me too. I'm always surprised by the complexity an unfriendliness of this tools.
