### ISSUE TITLE
Update needed to manual bibliography

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#90]
Hello!
Just a few things I noticed in STklos bibliography in the manual:

* *Chris Hanson -- The SOS Reference Manual, version 1.5 -- March, 1993.* This points to http://groups.csail.mit.edu/mac/projects/scheme/documentation/sos.html which seems to be broken. It looks like MIT Scheme, for example, ships the SOS manual with MIT Scheme itself: https://www.gnu.org/software/mit-scheme/documentation/stable/mit-scheme-sos.pdf
* *Gregor Kickzales -- Tiny-Clos -- December, 1992.* Looks like this one is also broken (the web ser ver does not respond)
* R5RS is mentioned in the references, but not R7RS...

**Comment by egallesio** [comment]
I have pushed a new version which correct this issue. 
Thanks for signaling the errors.

**Comment by jpellegrini** [comment]
Yes, I see the push! Fixed then...
