### ISSUE TITLE
Mention IDEs in the documentation?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#91]
There is old [Quack](https://www.neilvandyke.org/quack/) by Neil van Dyke, which still works fine, but it's not being updated...  And there is [Geiser](http://www.nongnu.org/geiser/), and it just got basic support for STklos (https://gitlab.com/emacs-geiser/stklos/)!

**Comment by egallesio** [comment]
Where do you think it should be documented. Is the Web site a good place?

**Comment by jpellegrini** [comment]
I suppose so. But the distribution could also have that in the README. Do you think it would be ok?

**Comment by jpellegrini** [comment]
It's in the README now. Maybe we could close this?

**Comment by egallesio** [comment]
Web site is also updated. 
I close it.
