### ISSUE TITLE
SRFI 193: Command lines

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#97]
SRFI 193 is due to be finalized soon. Would you be interested in having it in STklos?

**Comment by egallesio** [comment]
Hi @lassik,

It is implemented now in STklos. As requested, `command-line` is a parameter.

**Comment by jpellegrini** [comment]
Hi,

The spec says `command-name` should return a friendly version of `(car (command-line))`, and 

> If (car (command-line)) is a zero-length string, #f is returned to indicate "not a command".

But the STklos implementation doesn't do that:
```
stklos> (command-name)
""
```

**Comment by egallesio** [comment]
> But the STklos implementation doesn't do that.

Of course, you are right. I have inverted things. 
This is corrected now.

**Comment by egallesio** [comment]
May I close this issue?

**Comment by lassik** [comment]
Thanks a lot for implementing this SRFI, and sorry about the delay!

The current implementation is good enough to release.

`command-name` could perhaps check whether `file-suffix` is `".scm"` or `".stk"` and, if so, return the name without that suffix.

`load` from the REPL, or from the `-l` flag, should probably fill the filename in `script-file`.

**Comment by egallesio** [comment]
Hi @lassik,

No problem with the delay, I'm generally too slow  myself to blame someone for that :smiley: 

OK for suppressing the suffix.

> load from the REPL, or from the -l flag, should probably fill the filename in script-file.

I asked myseff this question, but I don't think so: files loaded with `-l` are generally not scripts but rather definition files. When you do 
```
stklos -l my-own-definition 
```
You are in the REPL and not really in a script. Furthermore, you can both use a `-l` and a `-f` to add some definitions before running yous script. In this case, of course, `command-name` returns the script name.

**Comment by lassik** [comment]
> I asked myseff this question, but I don't think so: files loaded with `-l` are generally not scripts but rather definition files. When you do
> 
> ```
> stklos -l my-own-definition 
> ```
> 
> You are in the REPL and not really in a script. Furthermore, you can both use a `-l` and a `-f` to add some definitions before running yous script.

I agree. However, if you write a script with `#! /usr/bin/env stklos` and a `main`, it's still useful to be able to `(load "...")` that script into a REPL for debugging.

It's no wonder that we are having these discussions. This was extremely hard to specify in the SRFI in such a way that every case works without surprises. I'm still not entirely happy with the result.

> In this case, of course, `command-name` returns the script name.

That's right. IMHO `command-name` is the right thing to use when checking whether we are running as a command line script.

**Comment by egallesio** [comment]
I have pushed a version which suppress the  suffix if its is a member of the list of suffixes which are implicitly added when loading a file (namely `("so" "ostk" "spi" "stk" "scm")`); otherwise the suffix is kept. 
This way `command-name` returns the prettier name which can be used for running the script.

**Comment by lassik** [comment]
> I have pushed a version which suppress the suffix if its is a member of the list of suffixes which are implicitly added when loading a file (namely `("so" "ostk" "spi" "stk" "scm")`); otherwise the suffix is kept.
> This way `command-name` returns the prettier name which can be used for running the script.

Sounds excellent! Thank you for doing this.

Is `so` just the normal Unix shared object extension (i.e. for loading FFI modules)?

What is the difference between the different extensions `scm`, `stk`, `ostk`, and `spi`?

**Comment by egallesio** [comment]
Sorry for the delay to answer you.

> Is `so` just the normal Unix shared object extension (i.e. for loading FFI modules)?

Yes it is, but this is just a suffix which is tried when loading a file as the other one. It is normally used for C compiled code, but nothing prevents you to use it with Scheme code. 

What is the difference between the different extensions scm, stk, ostk, and spi? Nothing normally

- scm is for compatibility with other systems
- stk is for STklos source files
- ostk is for compiled STklos files
- spi was used for defining the interface of Scheme package ScmPkag (https://www.stklos.net/~eg/Publis/dls07.pdf)  a thing of the past that Manuel Serrano and I designed and which is no more really used.

**Comment by lassik** [comment]
> Sorry for the delay to answer you.

No problem - we are all volunteers.

Thanks for the explanation. It makes sense. Removing any extension in `*load-suffixes*` is a good idea for cleaning up the command name.

The SRFI implementation seems complete so I'll close this issue.
